// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

module ChipTop(
  input         tl_slave_0_a_ready,
                tl_slave_0_d_valid,
  input  [2:0]  tl_slave_0_d_bits_opcode,
  input  [1:0]  tl_slave_0_d_bits_param,
  input  [2:0]  tl_slave_0_d_bits_size,
  input  [3:0]  tl_slave_0_d_bits_source,
  input         tl_slave_0_d_bits_sink,
                tl_slave_0_d_bits_denied,
  input  [63:0] tl_slave_0_d_bits_data,
  input         tl_slave_0_d_bits_corrupt,
                custom_boot,
                reset_io,
                clock_uncore_clock,
                jtag_TCK,
                jtag_TMS,
                jtag_TDI,
                spi_0_dq_0_i,
                spi_0_dq_1_i,
                spi_0_dq_2_i,
                spi_0_dq_3_i,
                uart_0_rxd,
                gpio_0_pins_0_i_ival,
                gpio_0_pins_0_i_po,
                gpio_0_pins_1_i_ival,
                gpio_0_pins_1_i_po,
                gpio_0_pins_2_i_ival,
                gpio_0_pins_2_i_po,
                gpio_0_pins_3_i_ival,
                gpio_0_pins_3_i_po,
                gpio_0_pins_4_i_ival,
                gpio_0_pins_4_i_po,
                gpio_0_pins_5_i_ival,
                gpio_0_pins_5_i_po,
                gpio_0_pins_6_i_ival,
                gpio_0_pins_6_i_po,
                gpio_0_pins_7_i_ival,
                gpio_0_pins_7_i_po,
                gpio_0_pins_8_i_ival,
                gpio_0_pins_8_i_po,
                gpio_0_pins_9_i_ival,
                gpio_0_pins_9_i_po,
                gpio_0_pins_10_i_ival,
                gpio_0_pins_10_i_po,
                gpio_0_pins_11_i_ival,
                gpio_0_pins_11_i_po,
                gpio_0_pins_12_i_ival,
                gpio_0_pins_12_i_po,
                gpio_0_pins_13_i_ival,
                gpio_0_pins_13_i_po,
                gpio_0_pins_14_i_ival,
                gpio_0_pins_14_i_po,
                gpio_0_pins_15_i_ival,
                gpio_0_pins_15_i_po,
  output        tl_slave_0_a_valid,
  output [2:0]  tl_slave_0_a_bits_opcode,
                tl_slave_0_a_bits_param,
                tl_slave_0_a_bits_size,
  output [3:0]  tl_slave_0_a_bits_source,
  output [31:0] tl_slave_0_a_bits_address,
  output [7:0]  tl_slave_0_a_bits_mask,
  output [63:0] tl_slave_0_a_bits_data,
  output        tl_slave_0_a_bits_corrupt,
                tl_slave_0_d_ready,
                jtag_TDO,
                spi_0_sck,
                spi_0_dq_0_o,
                spi_0_dq_0_ie,
                spi_0_dq_0_oe,
                spi_0_dq_1_o,
                spi_0_dq_1_ie,
                spi_0_dq_1_oe,
                spi_0_dq_2_o,
                spi_0_dq_2_ie,
                spi_0_dq_2_oe,
                spi_0_dq_3_o,
                spi_0_dq_3_ie,
                spi_0_dq_3_oe,
                spi_0_cs_0,
                uart_0_txd,
                gpio_0_pins_0_o_oval,
                gpio_0_pins_0_o_oe,
                gpio_0_pins_0_o_ie,
                gpio_0_pins_0_o_pue,
                gpio_0_pins_0_o_ds,
                gpio_0_pins_0_o_ps,
                gpio_0_pins_0_o_ds1,
                gpio_0_pins_0_o_poe,
                gpio_0_pins_1_o_oval,
                gpio_0_pins_1_o_oe,
                gpio_0_pins_1_o_ie,
                gpio_0_pins_1_o_pue,
                gpio_0_pins_1_o_ds,
                gpio_0_pins_1_o_ps,
                gpio_0_pins_1_o_ds1,
                gpio_0_pins_1_o_poe,
                gpio_0_pins_2_o_oval,
                gpio_0_pins_2_o_oe,
                gpio_0_pins_2_o_ie,
                gpio_0_pins_2_o_pue,
                gpio_0_pins_2_o_ds,
                gpio_0_pins_2_o_ps,
                gpio_0_pins_2_o_ds1,
                gpio_0_pins_2_o_poe,
                gpio_0_pins_3_o_oval,
                gpio_0_pins_3_o_oe,
                gpio_0_pins_3_o_ie,
                gpio_0_pins_3_o_pue,
                gpio_0_pins_3_o_ds,
                gpio_0_pins_3_o_ps,
                gpio_0_pins_3_o_ds1,
                gpio_0_pins_3_o_poe,
                gpio_0_pins_4_o_oval,
                gpio_0_pins_4_o_oe,
                gpio_0_pins_4_o_ie,
                gpio_0_pins_4_o_pue,
                gpio_0_pins_4_o_ds,
                gpio_0_pins_4_o_ps,
                gpio_0_pins_4_o_ds1,
                gpio_0_pins_4_o_poe,
                gpio_0_pins_5_o_oval,
                gpio_0_pins_5_o_oe,
                gpio_0_pins_5_o_ie,
                gpio_0_pins_5_o_pue,
                gpio_0_pins_5_o_ds,
                gpio_0_pins_5_o_ps,
                gpio_0_pins_5_o_ds1,
                gpio_0_pins_5_o_poe,
                gpio_0_pins_6_o_oval,
                gpio_0_pins_6_o_oe,
                gpio_0_pins_6_o_ie,
                gpio_0_pins_6_o_pue,
                gpio_0_pins_6_o_ds,
                gpio_0_pins_6_o_ps,
                gpio_0_pins_6_o_ds1,
                gpio_0_pins_6_o_poe,
                gpio_0_pins_7_o_oval,
                gpio_0_pins_7_o_oe,
                gpio_0_pins_7_o_ie,
                gpio_0_pins_7_o_pue,
                gpio_0_pins_7_o_ds,
                gpio_0_pins_7_o_ps,
                gpio_0_pins_7_o_ds1,
                gpio_0_pins_7_o_poe,
                gpio_0_pins_8_o_oval,
                gpio_0_pins_8_o_oe,
                gpio_0_pins_8_o_ie,
                gpio_0_pins_8_o_pue,
                gpio_0_pins_8_o_ds,
                gpio_0_pins_8_o_ps,
                gpio_0_pins_8_o_ds1,
                gpio_0_pins_8_o_poe,
                gpio_0_pins_9_o_oval,
                gpio_0_pins_9_o_oe,
                gpio_0_pins_9_o_ie,
                gpio_0_pins_9_o_pue,
                gpio_0_pins_9_o_ds,
                gpio_0_pins_9_o_ps,
                gpio_0_pins_9_o_ds1,
                gpio_0_pins_9_o_poe,
                gpio_0_pins_10_o_oval,
                gpio_0_pins_10_o_oe,
                gpio_0_pins_10_o_ie,
                gpio_0_pins_10_o_pue,
                gpio_0_pins_10_o_ds,
                gpio_0_pins_10_o_ps,
                gpio_0_pins_10_o_ds1,
                gpio_0_pins_10_o_poe,
                gpio_0_pins_11_o_oval,
                gpio_0_pins_11_o_oe,
                gpio_0_pins_11_o_ie,
                gpio_0_pins_11_o_pue,
                gpio_0_pins_11_o_ds,
                gpio_0_pins_11_o_ps,
                gpio_0_pins_11_o_ds1,
                gpio_0_pins_11_o_poe,
                gpio_0_pins_12_o_oval,
                gpio_0_pins_12_o_oe,
                gpio_0_pins_12_o_ie,
                gpio_0_pins_12_o_pue,
                gpio_0_pins_12_o_ds,
                gpio_0_pins_12_o_ps,
                gpio_0_pins_12_o_ds1,
                gpio_0_pins_12_o_poe,
                gpio_0_pins_13_o_oval,
                gpio_0_pins_13_o_oe,
                gpio_0_pins_13_o_ie,
                gpio_0_pins_13_o_pue,
                gpio_0_pins_13_o_ds,
                gpio_0_pins_13_o_ps,
                gpio_0_pins_13_o_ds1,
                gpio_0_pins_13_o_poe,
                gpio_0_pins_14_o_oval,
                gpio_0_pins_14_o_oe,
                gpio_0_pins_14_o_ie,
                gpio_0_pins_14_o_pue,
                gpio_0_pins_14_o_ds,
                gpio_0_pins_14_o_ps,
                gpio_0_pins_14_o_ds1,
                gpio_0_pins_14_o_poe,
                gpio_0_pins_15_o_oval,
                gpio_0_pins_15_o_oe,
                gpio_0_pins_15_o_ie,
                gpio_0_pins_15_o_pue,
                gpio_0_pins_15_o_ds,
                gpio_0_pins_15_o_ps,
                gpio_0_pins_15_o_ds1,
                gpio_0_pins_15_o_poe
);

  wire _iocell_jtag_TCK_i;	// @[IOCell.scala:111:23]
  wire _iocell_jtag_TMS_i;	// @[IOCell.scala:111:23]
  wire _iocell_jtag_TDI_i;	// @[IOCell.scala:111:23]
  wire _gated_clock_debug_clock_gate_out;	// @[ClockGate.scala:36:20]
  wire _dmactiveAck_dmactiveAck_io_q;	// @[ShiftReg.scala:45:23]
  wire _debug_reset_syncd_debug_reset_sync_io_q;	// @[ShiftReg.scala:45:23]
  wire _system_debug_systemjtag_reset_catcher_io_sync_reset;	// @[ResetCatchAndSync.scala:39:28]
  wire _iocell_custom_boot_i;	// @[IOCell.scala:111:23]
  wire _system_auto_implicitClockGrouper_out_clock;	// @[ChipTop.scala:28:35]
  wire _system_auto_implicitClockGrouper_out_reset;	// @[ChipTop.scala:28:35]
  wire _system_auto_subsystem_cbus_fixedClockNode_out_clock;	// @[ChipTop.scala:28:35]
  wire _system_auto_subsystem_cbus_fixedClockNode_out_reset;	// @[ChipTop.scala:28:35]
  wire _system_debug_systemjtag_jtag_TDO_data;	// @[ChipTop.scala:28:35]
  wire _system_debug_dmactive;	// @[ChipTop.scala:28:35]
  wire debug_reset = ~_debug_reset_syncd_debug_reset_sync_io_q;	// @[Periphery.scala:287:40, ShiftReg.scala:45:23]
  reg  clock_en;	// @[Periphery.scala:295:29]
  always @(posedge _system_auto_subsystem_cbus_fixedClockNode_out_clock or posedge debug_reset) begin	// @[ChipTop.scala:28:35, Periphery.scala:287:40]
    if (debug_reset)	// @[ChipTop.scala:28:35, Periphery.scala:287:40]
      clock_en <= 1'h1;	// @[IOCell.scala:220:30, Periphery.scala:295:29]
    else	// @[ChipTop.scala:28:35]
      clock_en <= _dmactiveAck_dmactiveAck_io_q;	// @[Periphery.scala:295:29, ShiftReg.scala:45:23]
  end // always @(posedge, posedge)
  `ifndef SYNTHESIS
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM_0;
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM_0 = `RANDOM;
        clock_en = _RANDOM_0[0];	// @[Periphery.scala:295:29]
      `endif // RANDOMIZE_REG_INIT
      `ifdef RANDOMIZE
        if (debug_reset)	// @[Periphery.scala:287:40]
          clock_en = 1'h1;	// @[IOCell.scala:220:30, Periphery.scala:295:29]
      `endif // RANDOMIZE
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // not def SYNTHESIS
  DigitalTop system (	// @[ChipTop.scala:28:35]
    .clock                                                                     (_system_auto_implicitClockGrouper_out_clock),	// @[ChipTop.scala:28:35]
    .reset                                                                     (_system_auto_implicitClockGrouper_out_reset),	// @[ChipTop.scala:28:35]
    .auto_prci_ctrl_domain_reset_setter_clock_in_member_allClocks_uncore_clock (clock_uncore_clock),
    .auto_prci_ctrl_domain_reset_setter_clock_in_member_allClocks_uncore_reset (reset_io),
    .resetctrl_hartIsInReset_0                                                 (_system_auto_subsystem_cbus_fixedClockNode_out_reset),	// @[ChipTop.scala:28:35]
    .debug_clock                                                               (_gated_clock_debug_clock_gate_out),	// @[ClockGate.scala:36:20]
    .debug_reset                                                               (debug_reset),	// @[Periphery.scala:287:40]
    .debug_systemjtag_jtag_TCK                                                 (_iocell_jtag_TCK_i),	// @[IOCell.scala:111:23]
    .debug_systemjtag_jtag_TMS                                                 (_iocell_jtag_TMS_i),	// @[IOCell.scala:111:23]
    .debug_systemjtag_jtag_TDI                                                 (_iocell_jtag_TDI_i),	// @[IOCell.scala:111:23]
    .debug_systemjtag_reset                                                    (_system_debug_systemjtag_reset_catcher_io_sync_reset),	// @[ResetCatchAndSync.scala:39:28]
    .debug_dmactiveAck                                                         (_dmactiveAck_dmactiveAck_io_q),	// @[ShiftReg.scala:45:23]
    .mem_tl_0_a_ready                                                          (tl_slave_0_a_ready),
    .mem_tl_0_d_valid                                                          (tl_slave_0_d_valid),
    .mem_tl_0_d_bits_opcode                                                    (tl_slave_0_d_bits_opcode),
    .mem_tl_0_d_bits_param                                                     (tl_slave_0_d_bits_param),
    .mem_tl_0_d_bits_size                                                      (tl_slave_0_d_bits_size),
    .mem_tl_0_d_bits_source                                                    (tl_slave_0_d_bits_source),
    .mem_tl_0_d_bits_sink                                                      (tl_slave_0_d_bits_sink),
    .mem_tl_0_d_bits_denied                                                    (tl_slave_0_d_bits_denied),
    .mem_tl_0_d_bits_data                                                      (tl_slave_0_d_bits_data),
    .mem_tl_0_d_bits_corrupt                                                   (tl_slave_0_d_bits_corrupt),
    .custom_boot                                                               (_iocell_custom_boot_i),	// @[IOCell.scala:111:23]
    .uart_0_rxd                                                                (uart_0_rxd),
    .gpio_0_pins_0_i_ival                                                      (gpio_0_pins_0_i_ival),
    .gpio_0_pins_1_i_ival                                                      (gpio_0_pins_1_i_ival),
    .gpio_0_pins_2_i_ival                                                      (gpio_0_pins_2_i_ival),
    .gpio_0_pins_3_i_ival                                                      (gpio_0_pins_3_i_ival),
    .gpio_0_pins_4_i_ival                                                      (gpio_0_pins_4_i_ival),
    .gpio_0_pins_5_i_ival                                                      (gpio_0_pins_5_i_ival),
    .gpio_0_pins_6_i_ival                                                      (gpio_0_pins_6_i_ival),
    .gpio_0_pins_7_i_ival                                                      (gpio_0_pins_7_i_ival),
    .gpio_0_pins_8_i_ival                                                      (gpio_0_pins_8_i_ival),
    .gpio_0_pins_9_i_ival                                                      (gpio_0_pins_9_i_ival),
    .gpio_0_pins_10_i_ival                                                     (gpio_0_pins_10_i_ival),
    .gpio_0_pins_11_i_ival                                                     (gpio_0_pins_11_i_ival),
    .gpio_0_pins_12_i_ival                                                     (gpio_0_pins_12_i_ival),
    .gpio_0_pins_13_i_ival                                                     (gpio_0_pins_13_i_ival),
    .gpio_0_pins_14_i_ival                                                     (gpio_0_pins_14_i_ival),
    .gpio_0_pins_15_i_ival                                                     (gpio_0_pins_15_i_ival),
    .spi_0_dq_0_i                                                              (spi_0_dq_0_i),
    .spi_0_dq_1_i                                                              (spi_0_dq_1_i),
    .spi_0_dq_2_i                                                              (spi_0_dq_2_i),
    .spi_0_dq_3_i                                                              (spi_0_dq_3_i),
    .auto_implicitClockGrouper_out_clock                                       (_system_auto_implicitClockGrouper_out_clock),
    .auto_implicitClockGrouper_out_reset                                       (_system_auto_implicitClockGrouper_out_reset),
    .auto_subsystem_cbus_fixedClockNode_out_clock                              (_system_auto_subsystem_cbus_fixedClockNode_out_clock),
    .auto_subsystem_cbus_fixedClockNode_out_reset                              (_system_auto_subsystem_cbus_fixedClockNode_out_reset),
    .debug_systemjtag_jtag_TDO_data                                            (_system_debug_systemjtag_jtag_TDO_data),
    .debug_dmactive                                                            (_system_debug_dmactive),
    .mem_tl_0_a_valid                                                          (tl_slave_0_a_valid),
    .mem_tl_0_a_bits_opcode                                                    (tl_slave_0_a_bits_opcode),
    .mem_tl_0_a_bits_param                                                     (tl_slave_0_a_bits_param),
    .mem_tl_0_a_bits_size                                                      (tl_slave_0_a_bits_size),
    .mem_tl_0_a_bits_source                                                    (tl_slave_0_a_bits_source),
    .mem_tl_0_a_bits_address                                                   (tl_slave_0_a_bits_address),
    .mem_tl_0_a_bits_mask                                                      (tl_slave_0_a_bits_mask),
    .mem_tl_0_a_bits_data                                                      (tl_slave_0_a_bits_data),
    .mem_tl_0_a_bits_corrupt                                                   (tl_slave_0_a_bits_corrupt),
    .mem_tl_0_d_ready                                                          (tl_slave_0_d_ready),
    .uart_0_txd                                                                (uart_0_txd),
    .gpio_0_pins_0_o_oval                                                      (gpio_0_pins_0_o_oval),
    .gpio_0_pins_0_o_oe                                                        (gpio_0_pins_0_o_oe),
    .gpio_0_pins_0_o_ie                                                        (gpio_0_pins_0_o_ie),
    .gpio_0_pins_0_o_pue                                                       (gpio_0_pins_0_o_pue),
    .gpio_0_pins_0_o_ds                                                        (gpio_0_pins_0_o_ds),
    .gpio_0_pins_0_o_ds1                                                       (gpio_0_pins_0_o_ds1),
    .gpio_0_pins_0_o_poe                                                       (gpio_0_pins_0_o_poe),
    .gpio_0_pins_1_o_oval                                                      (gpio_0_pins_1_o_oval),
    .gpio_0_pins_1_o_oe                                                        (gpio_0_pins_1_o_oe),
    .gpio_0_pins_1_o_ie                                                        (gpio_0_pins_1_o_ie),
    .gpio_0_pins_1_o_pue                                                       (gpio_0_pins_1_o_pue),
    .gpio_0_pins_1_o_ds                                                        (gpio_0_pins_1_o_ds),
    .gpio_0_pins_1_o_ds1                                                       (gpio_0_pins_1_o_ds1),
    .gpio_0_pins_1_o_poe                                                       (gpio_0_pins_1_o_poe),
    .gpio_0_pins_2_o_oval                                                      (gpio_0_pins_2_o_oval),
    .gpio_0_pins_2_o_oe                                                        (gpio_0_pins_2_o_oe),
    .gpio_0_pins_2_o_ie                                                        (gpio_0_pins_2_o_ie),
    .gpio_0_pins_2_o_pue                                                       (gpio_0_pins_2_o_pue),
    .gpio_0_pins_2_o_ds                                                        (gpio_0_pins_2_o_ds),
    .gpio_0_pins_2_o_ds1                                                       (gpio_0_pins_2_o_ds1),
    .gpio_0_pins_2_o_poe                                                       (gpio_0_pins_2_o_poe),
    .gpio_0_pins_3_o_oval                                                      (gpio_0_pins_3_o_oval),
    .gpio_0_pins_3_o_oe                                                        (gpio_0_pins_3_o_oe),
    .gpio_0_pins_3_o_ie                                                        (gpio_0_pins_3_o_ie),
    .gpio_0_pins_3_o_pue                                                       (gpio_0_pins_3_o_pue),
    .gpio_0_pins_3_o_ds                                                        (gpio_0_pins_3_o_ds),
    .gpio_0_pins_3_o_ds1                                                       (gpio_0_pins_3_o_ds1),
    .gpio_0_pins_3_o_poe                                                       (gpio_0_pins_3_o_poe),
    .gpio_0_pins_4_o_oval                                                      (gpio_0_pins_4_o_oval),
    .gpio_0_pins_4_o_oe                                                        (gpio_0_pins_4_o_oe),
    .gpio_0_pins_4_o_ie                                                        (gpio_0_pins_4_o_ie),
    .gpio_0_pins_4_o_pue                                                       (gpio_0_pins_4_o_pue),
    .gpio_0_pins_4_o_ds                                                        (gpio_0_pins_4_o_ds),
    .gpio_0_pins_4_o_ds1                                                       (gpio_0_pins_4_o_ds1),
    .gpio_0_pins_4_o_poe                                                       (gpio_0_pins_4_o_poe),
    .gpio_0_pins_5_o_oval                                                      (gpio_0_pins_5_o_oval),
    .gpio_0_pins_5_o_oe                                                        (gpio_0_pins_5_o_oe),
    .gpio_0_pins_5_o_ie                                                        (gpio_0_pins_5_o_ie),
    .gpio_0_pins_5_o_pue                                                       (gpio_0_pins_5_o_pue),
    .gpio_0_pins_5_o_ds                                                        (gpio_0_pins_5_o_ds),
    .gpio_0_pins_5_o_ds1                                                       (gpio_0_pins_5_o_ds1),
    .gpio_0_pins_5_o_poe                                                       (gpio_0_pins_5_o_poe),
    .gpio_0_pins_6_o_oval                                                      (gpio_0_pins_6_o_oval),
    .gpio_0_pins_6_o_oe                                                        (gpio_0_pins_6_o_oe),
    .gpio_0_pins_6_o_ie                                                        (gpio_0_pins_6_o_ie),
    .gpio_0_pins_6_o_pue                                                       (gpio_0_pins_6_o_pue),
    .gpio_0_pins_6_o_ds                                                        (gpio_0_pins_6_o_ds),
    .gpio_0_pins_6_o_ds1                                                       (gpio_0_pins_6_o_ds1),
    .gpio_0_pins_6_o_poe                                                       (gpio_0_pins_6_o_poe),
    .gpio_0_pins_7_o_oval                                                      (gpio_0_pins_7_o_oval),
    .gpio_0_pins_7_o_oe                                                        (gpio_0_pins_7_o_oe),
    .gpio_0_pins_7_o_ie                                                        (gpio_0_pins_7_o_ie),
    .gpio_0_pins_7_o_pue                                                       (gpio_0_pins_7_o_pue),
    .gpio_0_pins_7_o_ds                                                        (gpio_0_pins_7_o_ds),
    .gpio_0_pins_7_o_ds1                                                       (gpio_0_pins_7_o_ds1),
    .gpio_0_pins_7_o_poe                                                       (gpio_0_pins_7_o_poe),
    .gpio_0_pins_8_o_oval                                                      (gpio_0_pins_8_o_oval),
    .gpio_0_pins_8_o_oe                                                        (gpio_0_pins_8_o_oe),
    .gpio_0_pins_8_o_ie                                                        (gpio_0_pins_8_o_ie),
    .gpio_0_pins_8_o_pue                                                       (gpio_0_pins_8_o_pue),
    .gpio_0_pins_8_o_ds                                                        (gpio_0_pins_8_o_ds),
    .gpio_0_pins_8_o_ds1                                                       (gpio_0_pins_8_o_ds1),
    .gpio_0_pins_8_o_poe                                                       (gpio_0_pins_8_o_poe),
    .gpio_0_pins_9_o_oval                                                      (gpio_0_pins_9_o_oval),
    .gpio_0_pins_9_o_oe                                                        (gpio_0_pins_9_o_oe),
    .gpio_0_pins_9_o_ie                                                        (gpio_0_pins_9_o_ie),
    .gpio_0_pins_9_o_pue                                                       (gpio_0_pins_9_o_pue),
    .gpio_0_pins_9_o_ds                                                        (gpio_0_pins_9_o_ds),
    .gpio_0_pins_9_o_ds1                                                       (gpio_0_pins_9_o_ds1),
    .gpio_0_pins_9_o_poe                                                       (gpio_0_pins_9_o_poe),
    .gpio_0_pins_10_o_oval                                                     (gpio_0_pins_10_o_oval),
    .gpio_0_pins_10_o_oe                                                       (gpio_0_pins_10_o_oe),
    .gpio_0_pins_10_o_ie                                                       (gpio_0_pins_10_o_ie),
    .gpio_0_pins_10_o_pue                                                      (gpio_0_pins_10_o_pue),
    .gpio_0_pins_10_o_ds                                                       (gpio_0_pins_10_o_ds),
    .gpio_0_pins_10_o_ds1                                                      (gpio_0_pins_10_o_ds1),
    .gpio_0_pins_10_o_poe                                                      (gpio_0_pins_10_o_poe),
    .gpio_0_pins_11_o_oval                                                     (gpio_0_pins_11_o_oval),
    .gpio_0_pins_11_o_oe                                                       (gpio_0_pins_11_o_oe),
    .gpio_0_pins_11_o_ie                                                       (gpio_0_pins_11_o_ie),
    .gpio_0_pins_11_o_pue                                                      (gpio_0_pins_11_o_pue),
    .gpio_0_pins_11_o_ds                                                       (gpio_0_pins_11_o_ds),
    .gpio_0_pins_11_o_ds1                                                      (gpio_0_pins_11_o_ds1),
    .gpio_0_pins_11_o_poe                                                      (gpio_0_pins_11_o_poe),
    .gpio_0_pins_12_o_oval                                                     (gpio_0_pins_12_o_oval),
    .gpio_0_pins_12_o_oe                                                       (gpio_0_pins_12_o_oe),
    .gpio_0_pins_12_o_ie                                                       (gpio_0_pins_12_o_ie),
    .gpio_0_pins_12_o_pue                                                      (gpio_0_pins_12_o_pue),
    .gpio_0_pins_12_o_ds                                                       (gpio_0_pins_12_o_ds),
    .gpio_0_pins_12_o_ds1                                                      (gpio_0_pins_12_o_ds1),
    .gpio_0_pins_12_o_poe                                                      (gpio_0_pins_12_o_poe),
    .gpio_0_pins_13_o_oval                                                     (gpio_0_pins_13_o_oval),
    .gpio_0_pins_13_o_oe                                                       (gpio_0_pins_13_o_oe),
    .gpio_0_pins_13_o_ie                                                       (gpio_0_pins_13_o_ie),
    .gpio_0_pins_13_o_pue                                                      (gpio_0_pins_13_o_pue),
    .gpio_0_pins_13_o_ds                                                       (gpio_0_pins_13_o_ds),
    .gpio_0_pins_13_o_ds1                                                      (gpio_0_pins_13_o_ds1),
    .gpio_0_pins_13_o_poe                                                      (gpio_0_pins_13_o_poe),
    .gpio_0_pins_14_o_oval                                                     (gpio_0_pins_14_o_oval),
    .gpio_0_pins_14_o_oe                                                       (gpio_0_pins_14_o_oe),
    .gpio_0_pins_14_o_ie                                                       (gpio_0_pins_14_o_ie),
    .gpio_0_pins_14_o_pue                                                      (gpio_0_pins_14_o_pue),
    .gpio_0_pins_14_o_ds                                                       (gpio_0_pins_14_o_ds),
    .gpio_0_pins_14_o_ds1                                                      (gpio_0_pins_14_o_ds1),
    .gpio_0_pins_14_o_poe                                                      (gpio_0_pins_14_o_poe),
    .gpio_0_pins_15_o_oval                                                     (gpio_0_pins_15_o_oval),
    .gpio_0_pins_15_o_oe                                                       (gpio_0_pins_15_o_oe),
    .gpio_0_pins_15_o_ie                                                       (gpio_0_pins_15_o_ie),
    .gpio_0_pins_15_o_pue                                                      (gpio_0_pins_15_o_pue),
    .gpio_0_pins_15_o_ds                                                       (gpio_0_pins_15_o_ds),
    .gpio_0_pins_15_o_ds1                                                      (gpio_0_pins_15_o_ds1),
    .gpio_0_pins_15_o_poe                                                      (gpio_0_pins_15_o_poe),
    .spi_0_sck                                                                 (spi_0_sck),
    .spi_0_dq_0_o                                                              (spi_0_dq_0_o),
    .spi_0_dq_0_ie                                                             (spi_0_dq_0_ie),
    .spi_0_dq_0_oe                                                             (spi_0_dq_0_oe),
    .spi_0_dq_1_o                                                              (spi_0_dq_1_o),
    .spi_0_dq_1_ie                                                             (spi_0_dq_1_ie),
    .spi_0_dq_1_oe                                                             (spi_0_dq_1_oe),
    .spi_0_dq_2_o                                                              (spi_0_dq_2_o),
    .spi_0_dq_2_ie                                                             (spi_0_dq_2_ie),
    .spi_0_dq_2_oe                                                             (spi_0_dq_2_oe),
    .spi_0_dq_3_o                                                              (spi_0_dq_3_o),
    .spi_0_dq_3_ie                                                             (spi_0_dq_3_ie),
    .spi_0_dq_3_oe                                                             (spi_0_dq_3_oe),
    .spi_0_cs_0                                                                (spi_0_cs_0)
  );
  GenericDigitalInIOCell iocell_custom_boot (	// @[IOCell.scala:111:23]
    .pad (custom_boot),
    .ie  (1'h1),	// @[IOCell.scala:220:30]
    .i   (_iocell_custom_boot_i)
  );
  ResetCatchAndSync_d3 system_debug_systemjtag_reset_catcher (	// @[ResetCatchAndSync.scala:39:28]
    .clock         (_iocell_jtag_TCK_i),	// @[IOCell.scala:111:23]
    .reset         (_system_auto_subsystem_cbus_fixedClockNode_out_reset),	// @[ChipTop.scala:28:35]
    .io_sync_reset (_system_debug_systemjtag_reset_catcher_io_sync_reset)
  );
  AsyncResetSynchronizerShiftReg_w1_d3_i0 debug_reset_syncd_debug_reset_sync (	// @[ShiftReg.scala:45:23]
    .clock (_system_auto_subsystem_cbus_fixedClockNode_out_clock),	// @[ChipTop.scala:28:35]
    .reset (_system_debug_systemjtag_reset_catcher_io_sync_reset),	// @[ResetCatchAndSync.scala:39:28]
    .io_d  (1'h1),	// @[IOCell.scala:220:30]
    .io_q  (_debug_reset_syncd_debug_reset_sync_io_q)
  );
  ResetSynchronizerShiftReg_w1_d3_i0 dmactiveAck_dmactiveAck (	// @[ShiftReg.scala:45:23]
    .clock (_system_auto_subsystem_cbus_fixedClockNode_out_clock),	// @[ChipTop.scala:28:35]
    .reset (debug_reset),	// @[Periphery.scala:287:40]
    .io_d  (_system_debug_dmactive),	// @[ChipTop.scala:28:35]
    .io_q  (_dmactiveAck_dmactiveAck_io_q)
  );
  EICG_wrapper gated_clock_debug_clock_gate (	// @[ClockGate.scala:36:20]
    .in      (_system_auto_subsystem_cbus_fixedClockNode_out_clock),	// @[ChipTop.scala:28:35]
    .test_en (1'h0),	// @[ClockGate.scala:36:20]
    .en      (clock_en),	// @[Periphery.scala:295:29]
    .out     (_gated_clock_debug_clock_gate_out)
  );
  GenericDigitalOutIOCell iocell_jtag_TDO (	// @[IOCell.scala:112:24]
    .o   (_system_debug_systemjtag_jtag_TDO_data),	// @[ChipTop.scala:28:35]
    .oe  (1'h1),	// @[IOCell.scala:220:30]
    .pad (jtag_TDO)
  );
  GenericDigitalInIOCell iocell_jtag_TDI (	// @[IOCell.scala:111:23]
    .pad (jtag_TDI),
    .ie  (1'h1),	// @[IOCell.scala:220:30]
    .i   (_iocell_jtag_TDI_i)
  );
  GenericDigitalInIOCell iocell_jtag_TMS (	// @[IOCell.scala:111:23]
    .pad (jtag_TMS),
    .ie  (1'h1),	// @[IOCell.scala:220:30]
    .i   (_iocell_jtag_TMS_i)
  );
  GenericDigitalInIOCell iocell_jtag_TCK (	// @[IOCell.scala:111:23]
    .pad (jtag_TCK),
    .ie  (1'h1),	// @[IOCell.scala:220:30]
    .i   (_iocell_jtag_TCK_i)
  );
  assign gpio_0_pins_0_o_ps = 1'h0;	// @[ClockGate.scala:36:20]
  assign gpio_0_pins_1_o_ps = 1'h0;	// @[ClockGate.scala:36:20]
  assign gpio_0_pins_2_o_ps = 1'h0;	// @[ClockGate.scala:36:20]
  assign gpio_0_pins_3_o_ps = 1'h0;	// @[ClockGate.scala:36:20]
  assign gpio_0_pins_4_o_ps = 1'h0;	// @[ClockGate.scala:36:20]
  assign gpio_0_pins_5_o_ps = 1'h0;	// @[ClockGate.scala:36:20]
  assign gpio_0_pins_6_o_ps = 1'h0;	// @[ClockGate.scala:36:20]
  assign gpio_0_pins_7_o_ps = 1'h0;	// @[ClockGate.scala:36:20]
  assign gpio_0_pins_8_o_ps = 1'h0;	// @[ClockGate.scala:36:20]
  assign gpio_0_pins_9_o_ps = 1'h0;	// @[ClockGate.scala:36:20]
  assign gpio_0_pins_10_o_ps = 1'h0;	// @[ClockGate.scala:36:20]
  assign gpio_0_pins_11_o_ps = 1'h0;	// @[ClockGate.scala:36:20]
  assign gpio_0_pins_12_o_ps = 1'h0;	// @[ClockGate.scala:36:20]
  assign gpio_0_pins_13_o_ps = 1'h0;	// @[ClockGate.scala:36:20]
  assign gpio_0_pins_14_o_ps = 1'h0;	// @[ClockGate.scala:36:20]
  assign gpio_0_pins_15_o_ps = 1'h0;	// @[ClockGate.scala:36:20]
endmodule

