// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

module TLGPIO(
  input         clock,
                reset,
                auto_control_xing_in_a_valid,
  input  [2:0]  auto_control_xing_in_a_bits_opcode,
  input  [1:0]  auto_control_xing_in_a_bits_size,
  input  [6:0]  auto_control_xing_in_a_bits_source,
  input  [30:0] auto_control_xing_in_a_bits_address,
  input  [7:0]  auto_control_xing_in_a_bits_mask,
  input  [63:0] auto_control_xing_in_a_bits_data,
  input         auto_control_xing_in_d_ready,
                auto_io_out_pins_0_i_ival,
                auto_io_out_pins_1_i_ival,
                auto_io_out_pins_2_i_ival,
                auto_io_out_pins_3_i_ival,
                auto_io_out_pins_4_i_ival,
                auto_io_out_pins_5_i_ival,
                auto_io_out_pins_6_i_ival,
                auto_io_out_pins_7_i_ival,
                auto_io_out_pins_8_i_ival,
                auto_io_out_pins_9_i_ival,
                auto_io_out_pins_10_i_ival,
                auto_io_out_pins_11_i_ival,
                auto_io_out_pins_12_i_ival,
                auto_io_out_pins_13_i_ival,
                auto_io_out_pins_14_i_ival,
                auto_io_out_pins_15_i_ival,
  output        auto_int_xing_out_sync_0,
                auto_int_xing_out_sync_1,
                auto_int_xing_out_sync_2,
                auto_int_xing_out_sync_3,
                auto_int_xing_out_sync_4,
                auto_int_xing_out_sync_5,
                auto_int_xing_out_sync_6,
                auto_int_xing_out_sync_7,
                auto_int_xing_out_sync_8,
                auto_int_xing_out_sync_9,
                auto_int_xing_out_sync_10,
                auto_int_xing_out_sync_11,
                auto_int_xing_out_sync_12,
                auto_int_xing_out_sync_13,
                auto_int_xing_out_sync_14,
                auto_int_xing_out_sync_15,
                auto_control_xing_in_a_ready,
                auto_control_xing_in_d_valid,
  output [2:0]  auto_control_xing_in_d_bits_opcode,
  output [1:0]  auto_control_xing_in_d_bits_size,
  output [6:0]  auto_control_xing_in_d_bits_source,
  output [63:0] auto_control_xing_in_d_bits_data,
  output        auto_io_out_pins_0_o_oval,
                auto_io_out_pins_0_o_oe,
                auto_io_out_pins_0_o_ie,
                auto_io_out_pins_0_o_pue,
                auto_io_out_pins_0_o_ds,
                auto_io_out_pins_0_o_ds1,
                auto_io_out_pins_0_o_poe,
                auto_io_out_pins_1_o_oval,
                auto_io_out_pins_1_o_oe,
                auto_io_out_pins_1_o_ie,
                auto_io_out_pins_1_o_pue,
                auto_io_out_pins_1_o_ds,
                auto_io_out_pins_1_o_ds1,
                auto_io_out_pins_1_o_poe,
                auto_io_out_pins_2_o_oval,
                auto_io_out_pins_2_o_oe,
                auto_io_out_pins_2_o_ie,
                auto_io_out_pins_2_o_pue,
                auto_io_out_pins_2_o_ds,
                auto_io_out_pins_2_o_ds1,
                auto_io_out_pins_2_o_poe,
                auto_io_out_pins_3_o_oval,
                auto_io_out_pins_3_o_oe,
                auto_io_out_pins_3_o_ie,
                auto_io_out_pins_3_o_pue,
                auto_io_out_pins_3_o_ds,
                auto_io_out_pins_3_o_ds1,
                auto_io_out_pins_3_o_poe,
                auto_io_out_pins_4_o_oval,
                auto_io_out_pins_4_o_oe,
                auto_io_out_pins_4_o_ie,
                auto_io_out_pins_4_o_pue,
                auto_io_out_pins_4_o_ds,
                auto_io_out_pins_4_o_ds1,
                auto_io_out_pins_4_o_poe,
                auto_io_out_pins_5_o_oval,
                auto_io_out_pins_5_o_oe,
                auto_io_out_pins_5_o_ie,
                auto_io_out_pins_5_o_pue,
                auto_io_out_pins_5_o_ds,
                auto_io_out_pins_5_o_ds1,
                auto_io_out_pins_5_o_poe,
                auto_io_out_pins_6_o_oval,
                auto_io_out_pins_6_o_oe,
                auto_io_out_pins_6_o_ie,
                auto_io_out_pins_6_o_pue,
                auto_io_out_pins_6_o_ds,
                auto_io_out_pins_6_o_ds1,
                auto_io_out_pins_6_o_poe,
                auto_io_out_pins_7_o_oval,
                auto_io_out_pins_7_o_oe,
                auto_io_out_pins_7_o_ie,
                auto_io_out_pins_7_o_pue,
                auto_io_out_pins_7_o_ds,
                auto_io_out_pins_7_o_ds1,
                auto_io_out_pins_7_o_poe,
                auto_io_out_pins_8_o_oval,
                auto_io_out_pins_8_o_oe,
                auto_io_out_pins_8_o_ie,
                auto_io_out_pins_8_o_pue,
                auto_io_out_pins_8_o_ds,
                auto_io_out_pins_8_o_ds1,
                auto_io_out_pins_8_o_poe,
                auto_io_out_pins_9_o_oval,
                auto_io_out_pins_9_o_oe,
                auto_io_out_pins_9_o_ie,
                auto_io_out_pins_9_o_pue,
                auto_io_out_pins_9_o_ds,
                auto_io_out_pins_9_o_ds1,
                auto_io_out_pins_9_o_poe,
                auto_io_out_pins_10_o_oval,
                auto_io_out_pins_10_o_oe,
                auto_io_out_pins_10_o_ie,
                auto_io_out_pins_10_o_pue,
                auto_io_out_pins_10_o_ds,
                auto_io_out_pins_10_o_ds1,
                auto_io_out_pins_10_o_poe,
                auto_io_out_pins_11_o_oval,
                auto_io_out_pins_11_o_oe,
                auto_io_out_pins_11_o_ie,
                auto_io_out_pins_11_o_pue,
                auto_io_out_pins_11_o_ds,
                auto_io_out_pins_11_o_ds1,
                auto_io_out_pins_11_o_poe,
                auto_io_out_pins_12_o_oval,
                auto_io_out_pins_12_o_oe,
                auto_io_out_pins_12_o_ie,
                auto_io_out_pins_12_o_pue,
                auto_io_out_pins_12_o_ds,
                auto_io_out_pins_12_o_ds1,
                auto_io_out_pins_12_o_poe,
                auto_io_out_pins_13_o_oval,
                auto_io_out_pins_13_o_oe,
                auto_io_out_pins_13_o_ie,
                auto_io_out_pins_13_o_pue,
                auto_io_out_pins_13_o_ds,
                auto_io_out_pins_13_o_ds1,
                auto_io_out_pins_13_o_poe,
                auto_io_out_pins_14_o_oval,
                auto_io_out_pins_14_o_oe,
                auto_io_out_pins_14_o_ie,
                auto_io_out_pins_14_o_pue,
                auto_io_out_pins_14_o_ds,
                auto_io_out_pins_14_o_ds1,
                auto_io_out_pins_14_o_poe,
                auto_io_out_pins_15_o_oval,
                auto_io_out_pins_15_o_oe,
                auto_io_out_pins_15_o_ie,
                auto_io_out_pins_15_o_pue,
                auto_io_out_pins_15_o_ds,
                auto_io_out_pins_15_o_ds1,
                auto_io_out_pins_15_o_poe
);

  wire              out_woready_12;	// @[RegisterRouter.scala:83:24]
  wire              out_woready_6;	// @[RegisterRouter.scala:83:24]
  wire              _out_wofireMux_T_2;	// @[RegisterRouter.scala:83:24]
  wire              out_backSel_0;	// @[RegisterRouter.scala:83:24]
  wire [15:0]       _iofEnReg_io_q;	// @[GPIO.scala:104:25]
  wire [15:0]       _inSyncReg_inSyncReg_io_q;	// @[ShiftReg.scala:45:23]
  wire [15:0]       _poeReg_io_q;	// @[GPIO.scala:83:22]
  wire [15:0]       _ieReg_io_q;	// @[GPIO.scala:81:22]
  wire [15:0]       _pueReg_io_q;	// @[GPIO.scala:79:22]
  wire [15:0]       _oeReg_io_q;	// @[GPIO.scala:78:22]
  reg  [15:0]       portReg;	// @[GPIO.scala:76:20]
  reg  [15:0]       dsReg_0;	// @[GPIO.scala:80:23]
  reg  [15:0]       valueReg;	// @[GPIO.scala:89:23]
  reg  [15:0]       highIeReg;	// @[GPIO.scala:92:22]
  reg  [15:0]       lowIeReg;	// @[GPIO.scala:93:22]
  reg  [15:0]       riseIeReg;	// @[GPIO.scala:94:22]
  reg  [15:0]       fallIeReg;	// @[GPIO.scala:95:22]
  reg  [15:0]       highIpReg;	// @[GPIO.scala:96:22]
  reg  [15:0]       lowIpReg;	// @[GPIO.scala:97:22]
  reg  [15:0]       riseIpReg;	// @[GPIO.scala:98:22]
  reg  [15:0]       fallIpReg;	// @[GPIO.scala:99:22]
  reg  [15:0]       passthruHighIeReg;	// @[GPIO.scala:100:30]
  reg  [15:0]       passthruLowIeReg;	// @[GPIO.scala:101:30]
  reg  [15:0]       xorReg;	// @[GPIO.scala:108:22]
  wire              out_front_bits_read = auto_control_xing_in_a_bits_opcode == 3'h4;	// @[RegisterRouter.scala:72:36]
  wire              _out_out_bits_data_WIRE_10 = auto_control_xing_in_a_bits_address[11:7] == 5'h0;	// @[Edges.scala:192:34, RegisterRouter.scala:73:19, :83:24]
  wire [15:0]       _out_womask_T_19 = {{8{auto_control_xing_in_a_bits_mask[1]}}, {8{auto_control_xing_in_a_bits_mask[0]}}};	// @[Bitwise.scala:28:17, :77:12, RegisterRouter.scala:83:24]
  wire [15:0]       _out_womask_T_20 = {{8{auto_control_xing_in_a_bits_mask[5]}}, {8{auto_control_xing_in_a_bits_mask[4]}}};	// @[Bitwise.scala:28:17, :77:12, RegisterRouter.scala:83:24]
  assign out_backSel_0 = auto_control_xing_in_a_bits_address[6:3] == 4'h0;	// @[Cat.scala:33:92, OneHot.scala:57:35, RegisterRouter.scala:83:24]
  assign _out_wofireMux_T_2 = auto_control_xing_in_a_valid & auto_control_xing_in_d_ready & ~out_front_bits_read;	// @[RegisterRouter.scala:72:36, :83:24]
  assign out_woready_6 = _out_wofireMux_T_2 & auto_control_xing_in_a_bits_address[6:3] == 4'h1 & _out_out_bits_data_WIRE_10;	// @[Cat.scala:33:92, OneHot.scala:57:35, RegisterRouter.scala:83:24]
  assign out_woready_12 = _out_wofireMux_T_2 & auto_control_xing_in_a_bits_address[6:3] == 4'h2 & _out_out_bits_data_WIRE_10;	// @[Cat.scala:33:92, OneHot.scala:57:35, RegisterRouter.scala:83:24]
  wire              out_woready_16 = _out_wofireMux_T_2 & auto_control_xing_in_a_bits_address[6:3] == 4'h3 & _out_out_bits_data_WIRE_10;	// @[Cat.scala:33:92, OneHot.scala:57:35, RegisterRouter.scala:83:24]
  wire              out_woready_20 = _out_wofireMux_T_2 & auto_control_xing_in_a_bits_address[6:3] == 4'h4 & _out_out_bits_data_WIRE_10;	// @[Cat.scala:33:92, OneHot.scala:57:35, RegisterRouter.scala:83:24]
  wire              out_woready_3 = _out_wofireMux_T_2 & auto_control_xing_in_a_bits_address[6:3] == 4'h5 & _out_out_bits_data_WIRE_10;	// @[Cat.scala:33:92, OneHot.scala:57:35, RegisterRouter.scala:83:24]
  wire              out_woready_8 = _out_wofireMux_T_2 & auto_control_xing_in_a_bits_address[6:3] == 4'h6 & _out_out_bits_data_WIRE_10;	// @[Cat.scala:33:92, OneHot.scala:57:35, RegisterRouter.scala:83:24]
  wire              out_woready_18 = _out_wofireMux_T_2 & auto_control_xing_in_a_bits_address[6:3] == 4'h8 & _out_out_bits_data_WIRE_10;	// @[Cat.scala:33:92, OneHot.scala:57:35, RegisterRouter.scala:83:24]
  wire [15:0]       _GEN = {{1'h1}, {1'h1}, {1'h1}, {1'h1}, {1'h1}, {_out_out_bits_data_WIRE_10}, {_out_out_bits_data_WIRE_10}, {_out_out_bits_data_WIRE_10}, {_out_out_bits_data_WIRE_10}, {_out_out_bits_data_WIRE_10}, {_out_out_bits_data_WIRE_10}, {_out_out_bits_data_WIRE_10}, {_out_out_bits_data_WIRE_10}, {_out_out_bits_data_WIRE_10}, {_out_out_bits_data_WIRE_10}, {_out_out_bits_data_WIRE_10}};	// @[Buffer.scala:47:20, MuxLiteral.scala:49:10, RegisterRouter.scala:83:24]
  wire [15:0][47:0] _GEN_0 = {{48'h0}, {48'h0}, {48'h0}, {48'h0}, {48'h0}, {48'h0}, {{32'h0, passthruLowIeReg}}, {{passthruHighIeReg, 16'h0, xorReg}}, {48'h0}, {{lowIpReg, 16'h0, lowIeReg}}, {{highIpReg, 16'h0, highIeReg}}, {{fallIpReg, 16'h0, fallIeReg}}, {{riseIpReg, 16'h0, riseIeReg}}, {{dsReg_0, 16'h0, _pueReg_io_q}}, {{portReg, 16'h0, _oeReg_io_q}}, {{_ieReg_io_q, 16'h0, valueReg}}};	// @[Cat.scala:33:92, GPIO.scala:76:20, :78:22, :79:22, :80:23, :81:22, :89:23, :92:22, :93:22, :94:22, :95:22, :96:22, :97:22, :98:22, :99:22, :100:30, :101:30, :108:22, MuxLiteral.scala:49:10, RegisterRouter.scala:83:24]
  always @(posedge clock) begin
    if (reset) begin
      portReg <= 16'h0;	// @[GPIO.scala:76:20]
      dsReg_0 <= 16'h0;	// @[GPIO.scala:76:20, :80:23]
      valueReg <= 16'h0;	// @[GPIO.scala:76:20, :89:23]
      highIeReg <= 16'h0;	// @[GPIO.scala:76:20, :92:22]
      lowIeReg <= 16'h0;	// @[GPIO.scala:76:20, :93:22]
      riseIeReg <= 16'h0;	// @[GPIO.scala:76:20, :94:22]
      fallIeReg <= 16'h0;	// @[GPIO.scala:76:20, :95:22]
      highIpReg <= 16'h0;	// @[GPIO.scala:76:20, :96:22]
      lowIpReg <= 16'h0;	// @[GPIO.scala:76:20, :97:22]
      riseIpReg <= 16'h0;	// @[GPIO.scala:76:20, :98:22]
      fallIpReg <= 16'h0;	// @[GPIO.scala:76:20, :99:22]
      passthruHighIeReg <= 16'h0;	// @[GPIO.scala:76:20, :100:30]
      passthruLowIeReg <= 16'h0;	// @[GPIO.scala:76:20, :101:30]
      xorReg <= 16'h0;	// @[GPIO.scala:76:20, :108:22]
    end
    else begin
      if (out_woready_6 & (&_out_womask_T_20))	// @[RegisterRouter.scala:83:24]
        portReg <= auto_control_xing_in_a_bits_data[47:32];	// @[GPIO.scala:76:20, RegisterRouter.scala:83:24]
      if (out_woready_12 & (&_out_womask_T_20))	// @[RegisterRouter.scala:83:24]
        dsReg_0 <= auto_control_xing_in_a_bits_data[47:32];	// @[GPIO.scala:80:23, RegisterRouter.scala:83:24]
      valueReg <= _inSyncReg_inSyncReg_io_q;	// @[GPIO.scala:89:23, ShiftReg.scala:45:23]
      if (out_woready_3 & (&_out_womask_T_19))	// @[RegisterRouter.scala:83:24]
        highIeReg <= auto_control_xing_in_a_bits_data[15:0];	// @[GPIO.scala:92:22, RegisterRouter.scala:83:24]
      if (out_woready_8 & (&_out_womask_T_19))	// @[RegisterRouter.scala:83:24]
        lowIeReg <= auto_control_xing_in_a_bits_data[15:0];	// @[GPIO.scala:93:22, RegisterRouter.scala:83:24]
      if (out_woready_16 & (&_out_womask_T_19))	// @[RegisterRouter.scala:83:24]
        riseIeReg <= auto_control_xing_in_a_bits_data[15:0];	// @[GPIO.scala:94:22, RegisterRouter.scala:83:24]
      if (out_woready_20 & (&_out_womask_T_19))	// @[RegisterRouter.scala:83:24]
        fallIeReg <= auto_control_xing_in_a_bits_data[15:0];	// @[GPIO.scala:95:22, RegisterRouter.scala:83:24]
      highIpReg <= ~(~highIpReg | (out_woready_3 & (&_out_womask_T_20) ? auto_control_xing_in_a_bits_data[47:32] : 16'h0)) | valueReg;	// @[GPIO.scala:76:20, :89:23, :96:22, RegField.scala:128:{60,63,69,74,95}, RegisterRouter.scala:83:24]
      lowIpReg <= ~(~lowIpReg | (out_woready_8 & (&_out_womask_T_20) ? auto_control_xing_in_a_bits_data[47:32] : 16'h0)) | ~valueReg;	// @[GPIO.scala:76:20, :89:23, :97:22, :114:14, RegField.scala:128:{60,63,69,74,95}, RegisterRouter.scala:83:24]
      riseIpReg <= ~(~riseIpReg | (out_woready_16 & (&_out_womask_T_20) ? auto_control_xing_in_a_bits_data[47:32] : 16'h0)) | ~valueReg & _inSyncReg_inSyncReg_io_q;	// @[GPIO.scala:76:20, :89:23, :98:22, :114:{14,24}, RegField.scala:128:{60,63,69,74,95}, RegisterRouter.scala:83:24, ShiftReg.scala:45:23]
      fallIpReg <= ~(~fallIpReg | (out_woready_20 & (&_out_womask_T_20) ? auto_control_xing_in_a_bits_data[47:32] : 16'h0)) | valueReg & ~_inSyncReg_inSyncReg_io_q;	// @[GPIO.scala:76:20, :89:23, :99:22, :115:{23,25}, RegField.scala:128:{60,63,69,74,95}, RegisterRouter.scala:83:24, ShiftReg.scala:45:23]
      if (out_woready_18 & (&_out_womask_T_20))	// @[RegisterRouter.scala:83:24]
        passthruHighIeReg <= auto_control_xing_in_a_bits_data[47:32];	// @[GPIO.scala:100:30, RegisterRouter.scala:83:24]
      if (_out_wofireMux_T_2 & auto_control_xing_in_a_bits_address[6:3] == 4'h9 & _out_out_bits_data_WIRE_10 & (&_out_womask_T_19))	// @[Cat.scala:33:92, OneHot.scala:57:35, RegisterRouter.scala:83:24]
        passthruLowIeReg <= auto_control_xing_in_a_bits_data[15:0];	// @[GPIO.scala:101:30, RegisterRouter.scala:83:24]
      if (out_woready_18 & (&_out_womask_T_19))	// @[RegisterRouter.scala:83:24]
        xorReg <= auto_control_xing_in_a_bits_data[15:0];	// @[GPIO.scala:108:22, RegisterRouter.scala:83:24]
    end
  end // always @(posedge)
  `ifndef SYNTHESIS
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM_0;
    logic [31:0] _RANDOM_1;
    logic [31:0] _RANDOM_2;
    logic [31:0] _RANDOM_3;
    logic [31:0] _RANDOM_4;
    logic [31:0] _RANDOM_5;
    logic [31:0] _RANDOM_6;
    logic [31:0] _RANDOM_7;
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM_0 = `RANDOM;
        _RANDOM_1 = `RANDOM;
        _RANDOM_2 = `RANDOM;
        _RANDOM_3 = `RANDOM;
        _RANDOM_4 = `RANDOM;
        _RANDOM_5 = `RANDOM;
        _RANDOM_6 = `RANDOM;
        _RANDOM_7 = `RANDOM;
        portReg = _RANDOM_0[15:0];	// @[GPIO.scala:76:20]
        dsReg_0 = _RANDOM_0[31:16];	// @[GPIO.scala:76:20, :80:23]
        valueReg = _RANDOM_1[31:16];	// @[GPIO.scala:89:23]
        highIeReg = _RANDOM_2[15:0];	// @[GPIO.scala:92:22]
        lowIeReg = _RANDOM_2[31:16];	// @[GPIO.scala:92:22, :93:22]
        riseIeReg = _RANDOM_3[15:0];	// @[GPIO.scala:94:22]
        fallIeReg = _RANDOM_3[31:16];	// @[GPIO.scala:94:22, :95:22]
        highIpReg = _RANDOM_4[15:0];	// @[GPIO.scala:96:22]
        lowIpReg = _RANDOM_4[31:16];	// @[GPIO.scala:96:22, :97:22]
        riseIpReg = _RANDOM_5[15:0];	// @[GPIO.scala:98:22]
        fallIpReg = _RANDOM_5[31:16];	// @[GPIO.scala:98:22, :99:22]
        passthruHighIeReg = _RANDOM_6[15:0];	// @[GPIO.scala:100:30]
        passthruLowIeReg = _RANDOM_6[31:16];	// @[GPIO.scala:100:30, :101:30]
        xorReg = _RANDOM_7[31:16];	// @[GPIO.scala:108:22]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // not def SYNTHESIS
  IntSyncCrossingSource_8 intsource (	// @[Crossing.scala:28:31]
    .clock            (clock),
    .reset            (reset),
    .auto_in_0        (riseIpReg[0] & riseIeReg[0] | fallIpReg[0] & fallIeReg[0] | highIpReg[0] & highIeReg[0] | lowIpReg[0] & lowIeReg[0] | valueReg[0] & passthruHighIeReg[0] | ~(valueReg[0]) & passthruLowIeReg[0]),	// @[GPIO.scala:89:23, :92:22, :93:22, :94:22, :95:22, :96:22, :97:22, :98:22, :99:22, :100:30, :101:30, :236:{34,40,51}, :237:{36,42,53}, :238:{36,42,53}, :239:{35,41,51}, :240:{35,41,60,67}, :241:{27,42,60}]
    .auto_in_1        (riseIpReg[1] & riseIeReg[1] | fallIpReg[1] & fallIeReg[1] | highIpReg[1] & highIeReg[1] | lowIpReg[1] & lowIeReg[1] | valueReg[1] & passthruHighIeReg[1] | ~(valueReg[1]) & passthruLowIeReg[1]),	// @[GPIO.scala:89:23, :92:22, :93:22, :94:22, :95:22, :96:22, :97:22, :98:22, :99:22, :100:30, :101:30, :236:{34,40,51}, :237:{36,42,53}, :238:{36,42,53}, :239:{35,41,51}, :240:{35,41,60,67}, :241:{27,42,60}]
    .auto_in_2        (riseIpReg[2] & riseIeReg[2] | fallIpReg[2] & fallIeReg[2] | highIpReg[2] & highIeReg[2] | lowIpReg[2] & lowIeReg[2] | valueReg[2] & passthruHighIeReg[2] | ~(valueReg[2]) & passthruLowIeReg[2]),	// @[GPIO.scala:89:23, :92:22, :93:22, :94:22, :95:22, :96:22, :97:22, :98:22, :99:22, :100:30, :101:30, :236:{34,40,51}, :237:{36,42,53}, :238:{36,42,53}, :239:{35,41,51}, :240:{35,41,60,67}, :241:{27,42,60}]
    .auto_in_3        (riseIpReg[3] & riseIeReg[3] | fallIpReg[3] & fallIeReg[3] | highIpReg[3] & highIeReg[3] | lowIpReg[3] & lowIeReg[3] | valueReg[3] & passthruHighIeReg[3] | ~(valueReg[3]) & passthruLowIeReg[3]),	// @[GPIO.scala:89:23, :92:22, :93:22, :94:22, :95:22, :96:22, :97:22, :98:22, :99:22, :100:30, :101:30, :236:{34,40,51}, :237:{36,42,53}, :238:{36,42,53}, :239:{35,41,51}, :240:{35,41,60,67}, :241:{27,42,60}]
    .auto_in_4        (riseIpReg[4] & riseIeReg[4] | fallIpReg[4] & fallIeReg[4] | highIpReg[4] & highIeReg[4] | lowIpReg[4] & lowIeReg[4] | valueReg[4] & passthruHighIeReg[4] | ~(valueReg[4]) & passthruLowIeReg[4]),	// @[GPIO.scala:89:23, :92:22, :93:22, :94:22, :95:22, :96:22, :97:22, :98:22, :99:22, :100:30, :101:30, :236:{34,40,51}, :237:{36,42,53}, :238:{36,42,53}, :239:{35,41,51}, :240:{35,41,60,67}, :241:{27,42,60}]
    .auto_in_5        (riseIpReg[5] & riseIeReg[5] | fallIpReg[5] & fallIeReg[5] | highIpReg[5] & highIeReg[5] | lowIpReg[5] & lowIeReg[5] | valueReg[5] & passthruHighIeReg[5] | ~(valueReg[5]) & passthruLowIeReg[5]),	// @[GPIO.scala:89:23, :92:22, :93:22, :94:22, :95:22, :96:22, :97:22, :98:22, :99:22, :100:30, :101:30, :236:{34,40,51}, :237:{36,42,53}, :238:{36,42,53}, :239:{35,41,51}, :240:{35,41,60,67}, :241:{27,42,60}]
    .auto_in_6        (riseIpReg[6] & riseIeReg[6] | fallIpReg[6] & fallIeReg[6] | highIpReg[6] & highIeReg[6] | lowIpReg[6] & lowIeReg[6] | valueReg[6] & passthruHighIeReg[6] | ~(valueReg[6]) & passthruLowIeReg[6]),	// @[GPIO.scala:89:23, :92:22, :93:22, :94:22, :95:22, :96:22, :97:22, :98:22, :99:22, :100:30, :101:30, :236:{34,40,51}, :237:{36,42,53}, :238:{36,42,53}, :239:{35,41,51}, :240:{35,41,60,67}, :241:{27,42,60}]
    .auto_in_7        (riseIpReg[7] & riseIeReg[7] | fallIpReg[7] & fallIeReg[7] | highIpReg[7] & highIeReg[7] | lowIpReg[7] & lowIeReg[7] | valueReg[7] & passthruHighIeReg[7] | ~(valueReg[7]) & passthruLowIeReg[7]),	// @[GPIO.scala:89:23, :92:22, :93:22, :94:22, :95:22, :96:22, :97:22, :98:22, :99:22, :100:30, :101:30, :236:{34,40,51}, :237:{36,42,53}, :238:{36,42,53}, :239:{35,41,51}, :240:{35,41,60,67}, :241:{27,42,60}]
    .auto_in_8        (riseIpReg[8] & riseIeReg[8] | fallIpReg[8] & fallIeReg[8] | highIpReg[8] & highIeReg[8] | lowIpReg[8] & lowIeReg[8] | valueReg[8] & passthruHighIeReg[8] | ~(valueReg[8]) & passthruLowIeReg[8]),	// @[GPIO.scala:89:23, :92:22, :93:22, :94:22, :95:22, :96:22, :97:22, :98:22, :99:22, :100:30, :101:30, :236:{34,40,51}, :237:{36,42,53}, :238:{36,42,53}, :239:{35,41,51}, :240:{35,41,60,67}, :241:{27,42,60}]
    .auto_in_9        (riseIpReg[9] & riseIeReg[9] | fallIpReg[9] & fallIeReg[9] | highIpReg[9] & highIeReg[9] | lowIpReg[9] & lowIeReg[9] | valueReg[9] & passthruHighIeReg[9] | ~(valueReg[9]) & passthruLowIeReg[9]),	// @[GPIO.scala:89:23, :92:22, :93:22, :94:22, :95:22, :96:22, :97:22, :98:22, :99:22, :100:30, :101:30, :236:{34,40,51}, :237:{36,42,53}, :238:{36,42,53}, :239:{35,41,51}, :240:{35,41,60,67}, :241:{27,42,60}]
    .auto_in_10       (riseIpReg[10] & riseIeReg[10] | fallIpReg[10] & fallIeReg[10] | highIpReg[10] & highIeReg[10] | lowIpReg[10] & lowIeReg[10] | valueReg[10] & passthruHighIeReg[10] | ~(valueReg[10]) & passthruLowIeReg[10]),	// @[GPIO.scala:89:23, :92:22, :93:22, :94:22, :95:22, :96:22, :97:22, :98:22, :99:22, :100:30, :101:30, :236:{34,40,51}, :237:{36,42,53}, :238:{36,42,53}, :239:{35,41,51}, :240:{35,41,60,67}, :241:{27,42,60}]
    .auto_in_11       (riseIpReg[11] & riseIeReg[11] | fallIpReg[11] & fallIeReg[11] | highIpReg[11] & highIeReg[11] | lowIpReg[11] & lowIeReg[11] | valueReg[11] & passthruHighIeReg[11] | ~(valueReg[11]) & passthruLowIeReg[11]),	// @[GPIO.scala:89:23, :92:22, :93:22, :94:22, :95:22, :96:22, :97:22, :98:22, :99:22, :100:30, :101:30, :236:{34,40,51}, :237:{36,42,53}, :238:{36,42,53}, :239:{35,41,51}, :240:{35,41,60,67}, :241:{27,42,60}]
    .auto_in_12       (riseIpReg[12] & riseIeReg[12] | fallIpReg[12] & fallIeReg[12] | highIpReg[12] & highIeReg[12] | lowIpReg[12] & lowIeReg[12] | valueReg[12] & passthruHighIeReg[12] | ~(valueReg[12]) & passthruLowIeReg[12]),	// @[GPIO.scala:89:23, :92:22, :93:22, :94:22, :95:22, :96:22, :97:22, :98:22, :99:22, :100:30, :101:30, :236:{34,40,51}, :237:{36,42,53}, :238:{36,42,53}, :239:{35,41,51}, :240:{35,41,60,67}, :241:{27,42,60}]
    .auto_in_13       (riseIpReg[13] & riseIeReg[13] | fallIpReg[13] & fallIeReg[13] | highIpReg[13] & highIeReg[13] | lowIpReg[13] & lowIeReg[13] | valueReg[13] & passthruHighIeReg[13] | ~(valueReg[13]) & passthruLowIeReg[13]),	// @[GPIO.scala:89:23, :92:22, :93:22, :94:22, :95:22, :96:22, :97:22, :98:22, :99:22, :100:30, :101:30, :236:{34,40,51}, :237:{36,42,53}, :238:{36,42,53}, :239:{35,41,51}, :240:{35,41,60,67}, :241:{27,42,60}]
    .auto_in_14       (riseIpReg[14] & riseIeReg[14] | fallIpReg[14] & fallIeReg[14] | highIpReg[14] & highIeReg[14] | lowIpReg[14] & lowIeReg[14] | valueReg[14] & passthruHighIeReg[14] | ~(valueReg[14]) & passthruLowIeReg[14]),	// @[GPIO.scala:89:23, :92:22, :93:22, :94:22, :95:22, :96:22, :97:22, :98:22, :99:22, :100:30, :101:30, :236:{34,40,51}, :237:{36,42,53}, :238:{36,42,53}, :239:{35,41,51}, :240:{35,41,60,67}, :241:{27,42,60}]
    .auto_in_15       (riseIpReg[15] & riseIeReg[15] | fallIpReg[15] & fallIeReg[15] | highIpReg[15] & highIeReg[15] | lowIpReg[15] & lowIeReg[15] | valueReg[15] & passthruHighIeReg[15] | ~(valueReg[15]) & passthruLowIeReg[15]),	// @[GPIO.scala:89:23, :92:22, :93:22, :94:22, :95:22, :96:22, :97:22, :98:22, :99:22, :100:30, :101:30, :236:{34,40,51}, :237:{36,42,53}, :238:{36,42,53}, :239:{35,41,51}, :240:{35,41,60,67}, :241:{27,42,60}]
    .auto_out_sync_0  (auto_int_xing_out_sync_0),
    .auto_out_sync_1  (auto_int_xing_out_sync_1),
    .auto_out_sync_2  (auto_int_xing_out_sync_2),
    .auto_out_sync_3  (auto_int_xing_out_sync_3),
    .auto_out_sync_4  (auto_int_xing_out_sync_4),
    .auto_out_sync_5  (auto_int_xing_out_sync_5),
    .auto_out_sync_6  (auto_int_xing_out_sync_6),
    .auto_out_sync_7  (auto_int_xing_out_sync_7),
    .auto_out_sync_8  (auto_int_xing_out_sync_8),
    .auto_out_sync_9  (auto_int_xing_out_sync_9),
    .auto_out_sync_10 (auto_int_xing_out_sync_10),
    .auto_out_sync_11 (auto_int_xing_out_sync_11),
    .auto_out_sync_12 (auto_int_xing_out_sync_12),
    .auto_out_sync_13 (auto_int_xing_out_sync_13),
    .auto_out_sync_14 (auto_int_xing_out_sync_14),
    .auto_out_sync_15 (auto_int_xing_out_sync_15)
  );
  AsyncResetRegVec_w16_i0 oeReg (	// @[GPIO.scala:78:22]
    .clock (clock),
    .reset (reset),
    .io_d  (auto_control_xing_in_a_bits_data[15:0]),	// @[RegisterRouter.scala:83:24]
    .io_en (out_woready_6 & (&_out_womask_T_19)),	// @[RegisterRouter.scala:83:24]
    .io_q  (_oeReg_io_q)
  );
  AsyncResetRegVec_w16_i0 pueReg (	// @[GPIO.scala:79:22]
    .clock (clock),
    .reset (reset),
    .io_d  (auto_control_xing_in_a_bits_data[15:0]),	// @[RegisterRouter.scala:83:24]
    .io_en (out_woready_12 & (&_out_womask_T_19)),	// @[RegisterRouter.scala:83:24]
    .io_q  (_pueReg_io_q)
  );
  AsyncResetRegVec_w16_i0 ieReg (	// @[GPIO.scala:81:22]
    .clock (clock),
    .reset (reset),
    .io_d  (auto_control_xing_in_a_bits_data[47:32]),	// @[RegisterRouter.scala:83:24]
    .io_en (_out_wofireMux_T_2 & out_backSel_0 & _out_out_bits_data_WIRE_10 & (&_out_womask_T_20)),	// @[RegisterRouter.scala:83:24]
    .io_q  (_ieReg_io_q)
  );
  AsyncResetRegVec_w16_i0 poeReg (	// @[GPIO.scala:83:22]
    .clock (clock),
    .reset (reset),
    .io_d  (16'h0),	// @[GPIO.scala:76:20]
    .io_en (1'h0),
    .io_q  (_poeReg_io_q)
  );
  SynchronizerShiftReg_w16_d3 inSyncReg_inSyncReg (	// @[ShiftReg.scala:45:23]
    .clock (clock),
    .io_d  ({auto_io_out_pins_15_i_ival, auto_io_out_pins_14_i_ival, auto_io_out_pins_13_i_ival, auto_io_out_pins_12_i_ival, auto_io_out_pins_11_i_ival, auto_io_out_pins_10_i_ival, auto_io_out_pins_9_i_ival, auto_io_out_pins_8_i_ival, auto_io_out_pins_7_i_ival, auto_io_out_pins_6_i_ival, auto_io_out_pins_5_i_ival, auto_io_out_pins_4_i_ival, auto_io_out_pins_3_i_ival, auto_io_out_pins_2_i_ival, auto_io_out_pins_1_i_ival, auto_io_out_pins_0_i_ival}),	// @[GPIO.scala:87:41]
    .io_q  (_inSyncReg_inSyncReg_io_q)
  );
  AsyncResetRegVec_w16_i0 iofEnReg (	// @[GPIO.scala:104:25]
    .clock (clock),
    .reset (reset),
    .io_d  (16'h0),	// @[GPIO.scala:76:20]
    .io_en (1'h0),
    .io_q  (_iofEnReg_io_q)
  );
  assign auto_control_xing_in_a_ready = auto_control_xing_in_d_ready;
  assign auto_control_xing_in_d_valid = auto_control_xing_in_a_valid;
  assign auto_control_xing_in_d_bits_opcode = {2'h0, out_front_bits_read};	// @[RegisterRouter.scala:72:36, :98:19]
  assign auto_control_xing_in_d_bits_size = auto_control_xing_in_a_bits_size;
  assign auto_control_xing_in_d_bits_source = auto_control_xing_in_a_bits_source;
  assign auto_control_xing_in_d_bits_data = {16'h0, _GEN[auto_control_xing_in_a_bits_address[6:3]] ? _GEN_0[auto_control_xing_in_a_bits_address[6:3]] : 48'h0};	// @[Cat.scala:33:92, GPIO.scala:76:20, MuxLiteral.scala:49:10, RegisterRouter.scala:83:24]
  assign auto_io_out_pins_0_o_oval = portReg[0] ^ xorReg[0];	// @[GPIO.scala:76:20, :108:22, :197:37, :233:{43,51}]
  assign auto_io_out_pins_0_o_oe = _oeReg_io_q[0];	// @[GPIO.scala:78:22, :198:40]
  assign auto_io_out_pins_0_o_ie = _ieReg_io_q[0];	// @[GPIO.scala:81:22, :200:40]
  assign auto_io_out_pins_0_o_pue = _pueReg_io_q[0];	// @[GPIO.scala:79:22, :196:41]
  assign auto_io_out_pins_0_o_ds = dsReg_0[0];	// @[GPIO.scala:80:23, :199:38]
  assign auto_io_out_pins_0_o_ds1 = dsReg_0[0];	// @[GPIO.scala:80:23, :199:38]
  assign auto_io_out_pins_0_o_poe = _poeReg_io_q[0];	// @[GPIO.scala:83:22, :203:41]
  assign auto_io_out_pins_1_o_oval = portReg[1] ^ xorReg[1];	// @[GPIO.scala:76:20, :108:22, :197:37, :233:{43,51}]
  assign auto_io_out_pins_1_o_oe = _oeReg_io_q[1];	// @[GPIO.scala:78:22, :198:40]
  assign auto_io_out_pins_1_o_ie = _ieReg_io_q[1];	// @[GPIO.scala:81:22, :200:40]
  assign auto_io_out_pins_1_o_pue = _pueReg_io_q[1];	// @[GPIO.scala:79:22, :196:41]
  assign auto_io_out_pins_1_o_ds = dsReg_0[1];	// @[GPIO.scala:80:23, :199:38]
  assign auto_io_out_pins_1_o_ds1 = dsReg_0[1];	// @[GPIO.scala:80:23, :199:38]
  assign auto_io_out_pins_1_o_poe = _poeReg_io_q[1];	// @[GPIO.scala:83:22, :203:41]
  assign auto_io_out_pins_2_o_oval = portReg[2] ^ xorReg[2];	// @[GPIO.scala:76:20, :108:22, :197:37, :233:{43,51}]
  assign auto_io_out_pins_2_o_oe = _oeReg_io_q[2];	// @[GPIO.scala:78:22, :198:40]
  assign auto_io_out_pins_2_o_ie = _ieReg_io_q[2];	// @[GPIO.scala:81:22, :200:40]
  assign auto_io_out_pins_2_o_pue = _pueReg_io_q[2];	// @[GPIO.scala:79:22, :196:41]
  assign auto_io_out_pins_2_o_ds = dsReg_0[2];	// @[GPIO.scala:80:23, :199:38]
  assign auto_io_out_pins_2_o_ds1 = dsReg_0[2];	// @[GPIO.scala:80:23, :199:38]
  assign auto_io_out_pins_2_o_poe = _poeReg_io_q[2];	// @[GPIO.scala:83:22, :203:41]
  assign auto_io_out_pins_3_o_oval = portReg[3] ^ xorReg[3];	// @[GPIO.scala:76:20, :108:22, :197:37, :233:{43,51}]
  assign auto_io_out_pins_3_o_oe = _oeReg_io_q[3];	// @[GPIO.scala:78:22, :198:40]
  assign auto_io_out_pins_3_o_ie = _ieReg_io_q[3];	// @[GPIO.scala:81:22, :200:40]
  assign auto_io_out_pins_3_o_pue = _pueReg_io_q[3];	// @[GPIO.scala:79:22, :196:41]
  assign auto_io_out_pins_3_o_ds = dsReg_0[3];	// @[GPIO.scala:80:23, :199:38]
  assign auto_io_out_pins_3_o_ds1 = dsReg_0[3];	// @[GPIO.scala:80:23, :199:38]
  assign auto_io_out_pins_3_o_poe = _poeReg_io_q[3];	// @[GPIO.scala:83:22, :203:41]
  assign auto_io_out_pins_4_o_oval = portReg[4] ^ xorReg[4];	// @[GPIO.scala:76:20, :108:22, :197:37, :233:{43,51}]
  assign auto_io_out_pins_4_o_oe = _oeReg_io_q[4];	// @[GPIO.scala:78:22, :198:40]
  assign auto_io_out_pins_4_o_ie = _ieReg_io_q[4];	// @[GPIO.scala:81:22, :200:40]
  assign auto_io_out_pins_4_o_pue = _pueReg_io_q[4];	// @[GPIO.scala:79:22, :196:41]
  assign auto_io_out_pins_4_o_ds = dsReg_0[4];	// @[GPIO.scala:80:23, :199:38]
  assign auto_io_out_pins_4_o_ds1 = dsReg_0[4];	// @[GPIO.scala:80:23, :199:38]
  assign auto_io_out_pins_4_o_poe = _poeReg_io_q[4];	// @[GPIO.scala:83:22, :203:41]
  assign auto_io_out_pins_5_o_oval = portReg[5] ^ xorReg[5];	// @[GPIO.scala:76:20, :108:22, :197:37, :233:{43,51}]
  assign auto_io_out_pins_5_o_oe = _oeReg_io_q[5];	// @[GPIO.scala:78:22, :198:40]
  assign auto_io_out_pins_5_o_ie = _ieReg_io_q[5];	// @[GPIO.scala:81:22, :200:40]
  assign auto_io_out_pins_5_o_pue = _pueReg_io_q[5];	// @[GPIO.scala:79:22, :196:41]
  assign auto_io_out_pins_5_o_ds = dsReg_0[5];	// @[GPIO.scala:80:23, :199:38]
  assign auto_io_out_pins_5_o_ds1 = dsReg_0[5];	// @[GPIO.scala:80:23, :199:38]
  assign auto_io_out_pins_5_o_poe = _poeReg_io_q[5];	// @[GPIO.scala:83:22, :203:41]
  assign auto_io_out_pins_6_o_oval = portReg[6] ^ xorReg[6];	// @[GPIO.scala:76:20, :108:22, :197:37, :233:{43,51}]
  assign auto_io_out_pins_6_o_oe = _oeReg_io_q[6];	// @[GPIO.scala:78:22, :198:40]
  assign auto_io_out_pins_6_o_ie = _ieReg_io_q[6];	// @[GPIO.scala:81:22, :200:40]
  assign auto_io_out_pins_6_o_pue = _pueReg_io_q[6];	// @[GPIO.scala:79:22, :196:41]
  assign auto_io_out_pins_6_o_ds = dsReg_0[6];	// @[GPIO.scala:80:23, :199:38]
  assign auto_io_out_pins_6_o_ds1 = dsReg_0[6];	// @[GPIO.scala:80:23, :199:38]
  assign auto_io_out_pins_6_o_poe = _poeReg_io_q[6];	// @[GPIO.scala:83:22, :203:41]
  assign auto_io_out_pins_7_o_oval = portReg[7] ^ xorReg[7];	// @[GPIO.scala:76:20, :108:22, :197:37, :233:{43,51}]
  assign auto_io_out_pins_7_o_oe = _oeReg_io_q[7];	// @[GPIO.scala:78:22, :198:40]
  assign auto_io_out_pins_7_o_ie = _ieReg_io_q[7];	// @[GPIO.scala:81:22, :200:40]
  assign auto_io_out_pins_7_o_pue = _pueReg_io_q[7];	// @[GPIO.scala:79:22, :196:41]
  assign auto_io_out_pins_7_o_ds = dsReg_0[7];	// @[GPIO.scala:80:23, :199:38]
  assign auto_io_out_pins_7_o_ds1 = dsReg_0[7];	// @[GPIO.scala:80:23, :199:38]
  assign auto_io_out_pins_7_o_poe = _poeReg_io_q[7];	// @[GPIO.scala:83:22, :203:41]
  assign auto_io_out_pins_8_o_oval = portReg[8] ^ xorReg[8];	// @[GPIO.scala:76:20, :108:22, :197:37, :233:{43,51}]
  assign auto_io_out_pins_8_o_oe = _oeReg_io_q[8];	// @[GPIO.scala:78:22, :198:40]
  assign auto_io_out_pins_8_o_ie = _ieReg_io_q[8];	// @[GPIO.scala:81:22, :200:40]
  assign auto_io_out_pins_8_o_pue = _pueReg_io_q[8];	// @[GPIO.scala:79:22, :196:41]
  assign auto_io_out_pins_8_o_ds = dsReg_0[8];	// @[GPIO.scala:80:23, :199:38]
  assign auto_io_out_pins_8_o_ds1 = dsReg_0[8];	// @[GPIO.scala:80:23, :199:38]
  assign auto_io_out_pins_8_o_poe = _poeReg_io_q[8];	// @[GPIO.scala:83:22, :203:41]
  assign auto_io_out_pins_9_o_oval = portReg[9] ^ xorReg[9];	// @[GPIO.scala:76:20, :108:22, :197:37, :233:{43,51}]
  assign auto_io_out_pins_9_o_oe = _oeReg_io_q[9];	// @[GPIO.scala:78:22, :198:40]
  assign auto_io_out_pins_9_o_ie = _ieReg_io_q[9];	// @[GPIO.scala:81:22, :200:40]
  assign auto_io_out_pins_9_o_pue = _pueReg_io_q[9];	// @[GPIO.scala:79:22, :196:41]
  assign auto_io_out_pins_9_o_ds = dsReg_0[9];	// @[GPIO.scala:80:23, :199:38]
  assign auto_io_out_pins_9_o_ds1 = dsReg_0[9];	// @[GPIO.scala:80:23, :199:38]
  assign auto_io_out_pins_9_o_poe = _poeReg_io_q[9];	// @[GPIO.scala:83:22, :203:41]
  assign auto_io_out_pins_10_o_oval = portReg[10] ^ xorReg[10];	// @[GPIO.scala:76:20, :108:22, :197:37, :233:{43,51}]
  assign auto_io_out_pins_10_o_oe = _oeReg_io_q[10];	// @[GPIO.scala:78:22, :198:40]
  assign auto_io_out_pins_10_o_ie = _ieReg_io_q[10];	// @[GPIO.scala:81:22, :200:40]
  assign auto_io_out_pins_10_o_pue = _pueReg_io_q[10];	// @[GPIO.scala:79:22, :196:41]
  assign auto_io_out_pins_10_o_ds = dsReg_0[10];	// @[GPIO.scala:80:23, :199:38]
  assign auto_io_out_pins_10_o_ds1 = dsReg_0[10];	// @[GPIO.scala:80:23, :199:38]
  assign auto_io_out_pins_10_o_poe = _poeReg_io_q[10];	// @[GPIO.scala:83:22, :203:41]
  assign auto_io_out_pins_11_o_oval = portReg[11] ^ xorReg[11];	// @[GPIO.scala:76:20, :108:22, :197:37, :233:{43,51}]
  assign auto_io_out_pins_11_o_oe = _oeReg_io_q[11];	// @[GPIO.scala:78:22, :198:40]
  assign auto_io_out_pins_11_o_ie = _ieReg_io_q[11];	// @[GPIO.scala:81:22, :200:40]
  assign auto_io_out_pins_11_o_pue = _pueReg_io_q[11];	// @[GPIO.scala:79:22, :196:41]
  assign auto_io_out_pins_11_o_ds = dsReg_0[11];	// @[GPIO.scala:80:23, :199:38]
  assign auto_io_out_pins_11_o_ds1 = dsReg_0[11];	// @[GPIO.scala:80:23, :199:38]
  assign auto_io_out_pins_11_o_poe = _poeReg_io_q[11];	// @[GPIO.scala:83:22, :203:41]
  assign auto_io_out_pins_12_o_oval = portReg[12] ^ xorReg[12];	// @[GPIO.scala:76:20, :108:22, :197:37, :233:{43,51}]
  assign auto_io_out_pins_12_o_oe = _oeReg_io_q[12];	// @[GPIO.scala:78:22, :198:40]
  assign auto_io_out_pins_12_o_ie = _ieReg_io_q[12];	// @[GPIO.scala:81:22, :200:40]
  assign auto_io_out_pins_12_o_pue = _pueReg_io_q[12];	// @[GPIO.scala:79:22, :196:41]
  assign auto_io_out_pins_12_o_ds = dsReg_0[12];	// @[GPIO.scala:80:23, :199:38]
  assign auto_io_out_pins_12_o_ds1 = dsReg_0[12];	// @[GPIO.scala:80:23, :199:38]
  assign auto_io_out_pins_12_o_poe = _poeReg_io_q[12];	// @[GPIO.scala:83:22, :203:41]
  assign auto_io_out_pins_13_o_oval = portReg[13] ^ xorReg[13];	// @[GPIO.scala:76:20, :108:22, :197:37, :233:{43,51}]
  assign auto_io_out_pins_13_o_oe = _oeReg_io_q[13];	// @[GPIO.scala:78:22, :198:40]
  assign auto_io_out_pins_13_o_ie = _ieReg_io_q[13];	// @[GPIO.scala:81:22, :200:40]
  assign auto_io_out_pins_13_o_pue = _pueReg_io_q[13];	// @[GPIO.scala:79:22, :196:41]
  assign auto_io_out_pins_13_o_ds = dsReg_0[13];	// @[GPIO.scala:80:23, :199:38]
  assign auto_io_out_pins_13_o_ds1 = dsReg_0[13];	// @[GPIO.scala:80:23, :199:38]
  assign auto_io_out_pins_13_o_poe = _poeReg_io_q[13];	// @[GPIO.scala:83:22, :203:41]
  assign auto_io_out_pins_14_o_oval = portReg[14] ^ xorReg[14];	// @[GPIO.scala:76:20, :108:22, :197:37, :233:{43,51}]
  assign auto_io_out_pins_14_o_oe = _oeReg_io_q[14];	// @[GPIO.scala:78:22, :198:40]
  assign auto_io_out_pins_14_o_ie = _ieReg_io_q[14];	// @[GPIO.scala:81:22, :200:40]
  assign auto_io_out_pins_14_o_pue = _pueReg_io_q[14];	// @[GPIO.scala:79:22, :196:41]
  assign auto_io_out_pins_14_o_ds = dsReg_0[14];	// @[GPIO.scala:80:23, :199:38]
  assign auto_io_out_pins_14_o_ds1 = dsReg_0[14];	// @[GPIO.scala:80:23, :199:38]
  assign auto_io_out_pins_14_o_poe = _poeReg_io_q[14];	// @[GPIO.scala:83:22, :203:41]
  assign auto_io_out_pins_15_o_oval = portReg[15] ^ xorReg[15];	// @[GPIO.scala:76:20, :108:22, :197:37, :233:{43,51}]
  assign auto_io_out_pins_15_o_oe = _oeReg_io_q[15];	// @[GPIO.scala:78:22, :198:40]
  assign auto_io_out_pins_15_o_ie = _ieReg_io_q[15];	// @[GPIO.scala:81:22, :200:40]
  assign auto_io_out_pins_15_o_pue = _pueReg_io_q[15];	// @[GPIO.scala:79:22, :196:41]
  assign auto_io_out_pins_15_o_ds = dsReg_0[15];	// @[GPIO.scala:80:23, :199:38]
  assign auto_io_out_pins_15_o_ds1 = dsReg_0[15];	// @[GPIO.scala:80:23, :199:38]
  assign auto_io_out_pins_15_o_poe = _poeReg_io_q[15];	// @[GPIO.scala:83:22, :203:41]
endmodule

