// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

module TLPLIC(
  input         clock,
                reset,
                auto_int_in_0,
                auto_int_in_1,
                auto_int_in_2,
                auto_int_in_3,
                auto_int_in_4,
                auto_int_in_5,
                auto_int_in_6,
                auto_int_in_7,
                auto_int_in_8,
                auto_int_in_9,
                auto_int_in_10,
                auto_int_in_11,
                auto_int_in_12,
                auto_int_in_13,
                auto_int_in_14,
                auto_int_in_15,
                auto_int_in_16,
                auto_int_in_17,
                auto_in_a_valid,
  input  [2:0]  auto_in_a_bits_opcode,
  input  [1:0]  auto_in_a_bits_size,
  input  [6:0]  auto_in_a_bits_source,
  input  [27:0] auto_in_a_bits_address,
  input  [7:0]  auto_in_a_bits_mask,
  input  [63:0] auto_in_a_bits_data,
  input         auto_in_d_ready,
  output        auto_int_out_0,
                auto_in_a_ready,
                auto_in_d_valid,
  output [2:0]  auto_in_d_bits_opcode,
  output [1:0]  auto_in_d_bits_size,
  output [6:0]  auto_in_d_bits_source,
  output [63:0] auto_in_d_bits_data
);

  wire        out_woready_13;	// @[RegisterRouter.scala:83:24]
  wire        _out_wofireMux_T;	// @[RegisterRouter.scala:83:24]
  wire        out_backSel_64;	// @[RegisterRouter.scala:83:24]
  wire        completer_0;	// @[Plic.scala:295:35]
  wire [4:0]  completerDev;	// @[RegisterRouter.scala:83:24, package.scala:155:13]
  wire        _out_back_io_deq_valid;	// @[Decoupled.scala:375:21]
  wire        _out_back_io_deq_bits_read;	// @[Decoupled.scala:375:21]
  wire [22:0] _out_back_io_deq_bits_index;	// @[Decoupled.scala:375:21]
  wire [63:0] _out_back_io_deq_bits_data;	// @[Decoupled.scala:375:21]
  wire [7:0]  _out_back_io_deq_bits_mask;	// @[Decoupled.scala:375:21]
  wire [4:0]  _fanin_io_dev;	// @[Plic.scala:184:25]
  wire [2:0]  _fanin_io_max;	// @[Plic.scala:184:25]
  wire        _gateways_gateway_17_io_plic_valid;	// @[Plic.scala:156:27]
  wire        _gateways_gateway_16_io_plic_valid;	// @[Plic.scala:156:27]
  wire        _gateways_gateway_15_io_plic_valid;	// @[Plic.scala:156:27]
  wire        _gateways_gateway_14_io_plic_valid;	// @[Plic.scala:156:27]
  wire        _gateways_gateway_13_io_plic_valid;	// @[Plic.scala:156:27]
  wire        _gateways_gateway_12_io_plic_valid;	// @[Plic.scala:156:27]
  wire        _gateways_gateway_11_io_plic_valid;	// @[Plic.scala:156:27]
  wire        _gateways_gateway_10_io_plic_valid;	// @[Plic.scala:156:27]
  wire        _gateways_gateway_9_io_plic_valid;	// @[Plic.scala:156:27]
  wire        _gateways_gateway_8_io_plic_valid;	// @[Plic.scala:156:27]
  wire        _gateways_gateway_7_io_plic_valid;	// @[Plic.scala:156:27]
  wire        _gateways_gateway_6_io_plic_valid;	// @[Plic.scala:156:27]
  wire        _gateways_gateway_5_io_plic_valid;	// @[Plic.scala:156:27]
  wire        _gateways_gateway_4_io_plic_valid;	// @[Plic.scala:156:27]
  wire        _gateways_gateway_3_io_plic_valid;	// @[Plic.scala:156:27]
  wire        _gateways_gateway_2_io_plic_valid;	// @[Plic.scala:156:27]
  wire        _gateways_gateway_1_io_plic_valid;	// @[Plic.scala:156:27]
  wire        _gateways_gateway_io_plic_valid;	// @[Plic.scala:156:27]
  reg  [2:0]  priority_0;	// @[Plic.scala:163:31]
  reg  [2:0]  priority_1;	// @[Plic.scala:163:31]
  reg  [2:0]  priority_2;	// @[Plic.scala:163:31]
  reg  [2:0]  priority_3;	// @[Plic.scala:163:31]
  reg  [2:0]  priority_4;	// @[Plic.scala:163:31]
  reg  [2:0]  priority_5;	// @[Plic.scala:163:31]
  reg  [2:0]  priority_6;	// @[Plic.scala:163:31]
  reg  [2:0]  priority_7;	// @[Plic.scala:163:31]
  reg  [2:0]  priority_8;	// @[Plic.scala:163:31]
  reg  [2:0]  priority_9;	// @[Plic.scala:163:31]
  reg  [2:0]  priority_10;	// @[Plic.scala:163:31]
  reg  [2:0]  priority_11;	// @[Plic.scala:163:31]
  reg  [2:0]  priority_12;	// @[Plic.scala:163:31]
  reg  [2:0]  priority_13;	// @[Plic.scala:163:31]
  reg  [2:0]  priority_14;	// @[Plic.scala:163:31]
  reg  [2:0]  priority_15;	// @[Plic.scala:163:31]
  reg  [2:0]  priority_16;	// @[Plic.scala:163:31]
  reg  [2:0]  priority_17;	// @[Plic.scala:163:31]
  reg  [2:0]  threshold_0;	// @[Plic.scala:166:31]
  reg         pending_0;	// @[Plic.scala:168:26]
  reg         pending_1;	// @[Plic.scala:168:26]
  reg         pending_2;	// @[Plic.scala:168:26]
  reg         pending_3;	// @[Plic.scala:168:26]
  reg         pending_4;	// @[Plic.scala:168:26]
  reg         pending_5;	// @[Plic.scala:168:26]
  reg         pending_6;	// @[Plic.scala:168:26]
  reg         pending_7;	// @[Plic.scala:168:26]
  reg         pending_8;	// @[Plic.scala:168:26]
  reg         pending_9;	// @[Plic.scala:168:26]
  reg         pending_10;	// @[Plic.scala:168:26]
  reg         pending_11;	// @[Plic.scala:168:26]
  reg         pending_12;	// @[Plic.scala:168:26]
  reg         pending_13;	// @[Plic.scala:168:26]
  reg         pending_14;	// @[Plic.scala:168:26]
  reg         pending_15;	// @[Plic.scala:168:26]
  reg         pending_16;	// @[Plic.scala:168:26]
  reg         pending_17;	// @[Plic.scala:168:26]
  reg  [6:0]  enables_0_0;	// @[Plic.scala:174:26]
  reg  [7:0]  enables_0_1;	// @[Plic.scala:175:50]
  reg  [2:0]  enables_0_2;	// @[Plic.scala:176:51]
  reg  [4:0]  maxDevs_0;	// @[Plic.scala:181:22]
  reg  [2:0]  x1_0_REG;	// @[Plic.scala:188:45]
  wire [31:0] _completedDevs_T = 32'h1 << completerDev;	// @[OneHot.scala:64:12, RegisterRouter.scala:83:24, package.scala:155:13]
  wire [17:0] _GEN = completer_0 ? _completedDevs_T[18:1] : 18'h0;	// @[OneHot.scala:64:{12,27}, Plic.scala:264:28, :295:35, RegisterRouter.scala:83:24]
  wire        _out_T_25 = {_out_back_io_deq_bits_index[22:19], _out_back_io_deq_bits_index[17:11], _out_back_io_deq_bits_index[8:4]} == 16'h0;	// @[Decoupled.scala:375:21, RegisterRouter.scala:83:24]
  wire [31:0] _out_womask_T_13 = {{8{_out_back_io_deq_bits_mask[7]}}, {8{_out_back_io_deq_bits_mask[6]}}, {8{_out_back_io_deq_bits_mask[5]}}, {8{_out_back_io_deq_bits_mask[4]}}};	// @[Bitwise.scala:28:17, :77:12, Decoupled.scala:375:21, RegisterRouter.scala:83:24]
  wire        claimer_0 = _out_wofireMux_T & _out_back_io_deq_bits_read & out_backSel_64 & _out_T_25 & (|_out_womask_T_13);	// @[Decoupled.scala:375:21, RegisterRouter.scala:83:24]
  assign completerDev = _out_back_io_deq_bits_data[36:32];	// @[Decoupled.scala:375:21, RegisterRouter.scala:83:24, package.scala:155:13]
  wire [18:0] _out_completer_0_T = {enables_0_2, enables_0_1, enables_0_0, 1'h0} >> completerDev;	// @[Cat.scala:33:92, Plic.scala:163:31, :174:26, :175:50, :176:51, :295:51, RegisterRouter.scala:83:24, package.scala:155:13]
  assign completer_0 = out_woready_13 & (&_out_womask_T_13) & _out_completer_0_T[0];	// @[Plic.scala:295:{35,51}, RegisterRouter.scala:83:24]
  wire [6:0]  out_oindex = {_out_back_io_deq_bits_index[18], _out_back_io_deq_bits_index[10:9], _out_back_io_deq_bits_index[3:0]};	// @[Cat.scala:33:92, Decoupled.scala:375:21, RegisterRouter.scala:83:24]
  wire [6:0]  _GEN_0 = {_out_back_io_deq_bits_index[18], _out_back_io_deq_bits_index[10:9], _out_back_io_deq_bits_index[3:0]};	// @[Cat.scala:33:92, Decoupled.scala:375:21, OneHot.scala:57:35, RegisterRouter.scala:83:24]
  assign out_backSel_64 = _GEN_0 == 7'h40;	// @[MuxLiteral.scala:54:22, OneHot.scala:57:35, RegisterRouter.scala:83:24]
  assign _out_wofireMux_T = _out_back_io_deq_valid & auto_in_d_ready;	// @[Decoupled.scala:375:21, RegisterRouter.scala:83:24]
  wire        _out_wofireMux_T_2 = _out_wofireMux_T & ~_out_back_io_deq_bits_read;	// @[Decoupled.scala:375:21, RegisterRouter.scala:83:24]
  wire        out_woready_3 = _out_wofireMux_T_2 & _GEN_0 == 7'h1 & _out_T_25;	// @[MuxLiteral.scala:54:22, OneHot.scala:57:35, RegisterRouter.scala:83:24]
  wire        out_woready_6 = _out_wofireMux_T_2 & _GEN_0 == 7'h2 & _out_T_25;	// @[MuxLiteral.scala:54:22, OneHot.scala:57:35, RegisterRouter.scala:83:24]
  wire        out_woready_10 = _out_wofireMux_T_2 & _GEN_0 == 7'h3 & _out_T_25;	// @[MuxLiteral.scala:54:22, OneHot.scala:57:35, RegisterRouter.scala:83:24]
  wire        out_woready_17 = _out_wofireMux_T_2 & _GEN_0 == 7'h4 & _out_T_25;	// @[MuxLiteral.scala:54:22, OneHot.scala:57:35, RegisterRouter.scala:83:24]
  wire        out_woready_1 = _out_wofireMux_T_2 & _GEN_0 == 7'h5 & _out_T_25;	// @[MuxLiteral.scala:54:22, OneHot.scala:57:35, RegisterRouter.scala:83:24]
  wire        out_woready_24 = _out_wofireMux_T_2 & _GEN_0 == 7'h6 & _out_T_25;	// @[MuxLiteral.scala:54:22, OneHot.scala:57:35, RegisterRouter.scala:83:24]
  wire        out_woready_8 = _out_wofireMux_T_2 & _GEN_0 == 7'h7 & _out_T_25;	// @[MuxLiteral.scala:54:22, OneHot.scala:57:35, RegisterRouter.scala:83:24]
  wire        out_woready_15 = _out_wofireMux_T_2 & _GEN_0 == 7'h8 & _out_T_25;	// @[MuxLiteral.scala:54:22, OneHot.scala:57:35, RegisterRouter.scala:83:24]
  wire        out_woready_21 = _out_wofireMux_T_2 & _GEN_0 == 7'h20 & _out_T_25;	// @[MuxLiteral.scala:54:22, OneHot.scala:57:35, RegisterRouter.scala:83:24]
  assign out_woready_13 = _out_wofireMux_T_2 & out_backSel_64 & _out_T_25;	// @[RegisterRouter.scala:83:24]
  wire        _out_out_bits_data_T_13 = out_oindex == 7'h0;	// @[Cat.scala:33:92, MuxLiteral.scala:54:22]
  wire [4:0]  claiming = claimer_0 ? maxDevs_0 : 5'h0;	// @[Plic.scala:181:22, :246:49, RegisterRouter.scala:83:24]
  wire        claimedDevs_1 = claiming == 5'h1;	// @[OneHot.scala:64:{12,27}, Plic.scala:246:49, :247:62]
  wire        claimedDevs_2 = claiming == 5'h2;	// @[OneHot.scala:64:{12,27}, Plic.scala:246:49, :247:62]
  wire        claimedDevs_3 = claiming == 5'h3;	// @[OneHot.scala:64:{12,27}, Plic.scala:246:49, :247:62]
  wire        claimedDevs_4 = claiming == 5'h4;	// @[OneHot.scala:64:{12,27}, Plic.scala:246:49, :247:62]
  wire        claimedDevs_5 = claiming == 5'h5;	// @[OneHot.scala:64:{12,27}, Plic.scala:246:49, :247:62]
  wire        claimedDevs_6 = claiming == 5'h6;	// @[OneHot.scala:64:{12,27}, Plic.scala:246:49, :247:62]
  wire        claimedDevs_7 = claiming == 5'h7;	// @[OneHot.scala:64:{12,27}, Plic.scala:246:49, :247:62]
  wire        claimedDevs_8 = claiming == 5'h8;	// @[OneHot.scala:64:{12,27}, Plic.scala:246:49, :247:62]
  wire        claimedDevs_9 = claiming == 5'h9;	// @[OneHot.scala:64:{12,27}, Plic.scala:246:49, :247:62]
  wire        claimedDevs_10 = claiming == 5'hA;	// @[OneHot.scala:64:{12,27}, Plic.scala:246:49, :247:62]
  wire        claimedDevs_11 = claiming == 5'hB;	// @[OneHot.scala:64:{12,27}, Plic.scala:246:49, :247:62]
  wire        claimedDevs_12 = claiming == 5'hC;	// @[OneHot.scala:64:{12,27}, Plic.scala:246:49, :247:62]
  wire        claimedDevs_13 = claiming == 5'hD;	// @[OneHot.scala:64:{12,27}, Plic.scala:246:49, :247:62]
  wire        claimedDevs_14 = claiming == 5'hE;	// @[OneHot.scala:64:{12,27}, Plic.scala:246:49, :247:62]
  wire        claimedDevs_15 = claiming == 5'hF;	// @[OneHot.scala:64:{12,27}, Plic.scala:246:49, :247:62]
  wire        claimedDevs_16 = claiming == 5'h10;	// @[OneHot.scala:64:{12,27}, Plic.scala:246:49, :247:62]
  wire        claimedDevs_17 = claiming == 5'h11;	// @[OneHot.scala:64:{12,27}, Plic.scala:246:49, :247:62]
  wire        claimedDevs_18 = claiming == 5'h12;	// @[OneHot.scala:64:{12,27}, Plic.scala:246:49, :247:62]
  always @(posedge clock) begin
    if (_out_wofireMux_T_2 & _GEN_0 == 7'h0 & _out_T_25 & _out_back_io_deq_bits_mask[4])	// @[Bitwise.scala:28:17, Decoupled.scala:375:21, MuxLiteral.scala:54:22, OneHot.scala:57:35, RegisterRouter.scala:83:24]
      priority_0 <= _out_back_io_deq_bits_data[34:32];	// @[Decoupled.scala:375:21, Plic.scala:163:31, RegisterRouter.scala:83:24]
    if (out_woready_3 & _out_back_io_deq_bits_mask[0])	// @[Bitwise.scala:28:17, Decoupled.scala:375:21, RegisterRouter.scala:83:24]
      priority_1 <= _out_back_io_deq_bits_data[2:0];	// @[Decoupled.scala:375:21, Plic.scala:163:31, RegisterRouter.scala:83:24]
    if (out_woready_3 & _out_back_io_deq_bits_mask[4])	// @[Bitwise.scala:28:17, Decoupled.scala:375:21, RegisterRouter.scala:83:24]
      priority_2 <= _out_back_io_deq_bits_data[34:32];	// @[Decoupled.scala:375:21, Plic.scala:163:31, RegisterRouter.scala:83:24]
    if (out_woready_6 & _out_back_io_deq_bits_mask[0])	// @[Bitwise.scala:28:17, Decoupled.scala:375:21, RegisterRouter.scala:83:24]
      priority_3 <= _out_back_io_deq_bits_data[2:0];	// @[Decoupled.scala:375:21, Plic.scala:163:31, RegisterRouter.scala:83:24]
    if (out_woready_6 & _out_back_io_deq_bits_mask[4])	// @[Bitwise.scala:28:17, Decoupled.scala:375:21, RegisterRouter.scala:83:24]
      priority_4 <= _out_back_io_deq_bits_data[34:32];	// @[Decoupled.scala:375:21, Plic.scala:163:31, RegisterRouter.scala:83:24]
    if (out_woready_10 & _out_back_io_deq_bits_mask[0])	// @[Bitwise.scala:28:17, Decoupled.scala:375:21, RegisterRouter.scala:83:24]
      priority_5 <= _out_back_io_deq_bits_data[2:0];	// @[Decoupled.scala:375:21, Plic.scala:163:31, RegisterRouter.scala:83:24]
    if (out_woready_10 & _out_back_io_deq_bits_mask[4])	// @[Bitwise.scala:28:17, Decoupled.scala:375:21, RegisterRouter.scala:83:24]
      priority_6 <= _out_back_io_deq_bits_data[34:32];	// @[Decoupled.scala:375:21, Plic.scala:163:31, RegisterRouter.scala:83:24]
    if (out_woready_17 & _out_back_io_deq_bits_mask[0])	// @[Bitwise.scala:28:17, Decoupled.scala:375:21, RegisterRouter.scala:83:24]
      priority_7 <= _out_back_io_deq_bits_data[2:0];	// @[Decoupled.scala:375:21, Plic.scala:163:31, RegisterRouter.scala:83:24]
    if (out_woready_17 & _out_back_io_deq_bits_mask[4])	// @[Bitwise.scala:28:17, Decoupled.scala:375:21, RegisterRouter.scala:83:24]
      priority_8 <= _out_back_io_deq_bits_data[34:32];	// @[Decoupled.scala:375:21, Plic.scala:163:31, RegisterRouter.scala:83:24]
    if (out_woready_1 & _out_back_io_deq_bits_mask[0])	// @[Bitwise.scala:28:17, Decoupled.scala:375:21, RegisterRouter.scala:83:24]
      priority_9 <= _out_back_io_deq_bits_data[2:0];	// @[Decoupled.scala:375:21, Plic.scala:163:31, RegisterRouter.scala:83:24]
    if (out_woready_1 & _out_back_io_deq_bits_mask[4])	// @[Bitwise.scala:28:17, Decoupled.scala:375:21, RegisterRouter.scala:83:24]
      priority_10 <= _out_back_io_deq_bits_data[34:32];	// @[Decoupled.scala:375:21, Plic.scala:163:31, RegisterRouter.scala:83:24]
    if (out_woready_24 & _out_back_io_deq_bits_mask[0])	// @[Bitwise.scala:28:17, Decoupled.scala:375:21, RegisterRouter.scala:83:24]
      priority_11 <= _out_back_io_deq_bits_data[2:0];	// @[Decoupled.scala:375:21, Plic.scala:163:31, RegisterRouter.scala:83:24]
    if (out_woready_24 & _out_back_io_deq_bits_mask[4])	// @[Bitwise.scala:28:17, Decoupled.scala:375:21, RegisterRouter.scala:83:24]
      priority_12 <= _out_back_io_deq_bits_data[34:32];	// @[Decoupled.scala:375:21, Plic.scala:163:31, RegisterRouter.scala:83:24]
    if (out_woready_8 & _out_back_io_deq_bits_mask[0])	// @[Bitwise.scala:28:17, Decoupled.scala:375:21, RegisterRouter.scala:83:24]
      priority_13 <= _out_back_io_deq_bits_data[2:0];	// @[Decoupled.scala:375:21, Plic.scala:163:31, RegisterRouter.scala:83:24]
    if (out_woready_8 & _out_back_io_deq_bits_mask[4])	// @[Bitwise.scala:28:17, Decoupled.scala:375:21, RegisterRouter.scala:83:24]
      priority_14 <= _out_back_io_deq_bits_data[34:32];	// @[Decoupled.scala:375:21, Plic.scala:163:31, RegisterRouter.scala:83:24]
    if (out_woready_15 & _out_back_io_deq_bits_mask[0])	// @[Bitwise.scala:28:17, Decoupled.scala:375:21, RegisterRouter.scala:83:24]
      priority_15 <= _out_back_io_deq_bits_data[2:0];	// @[Decoupled.scala:375:21, Plic.scala:163:31, RegisterRouter.scala:83:24]
    if (out_woready_15 & _out_back_io_deq_bits_mask[4])	// @[Bitwise.scala:28:17, Decoupled.scala:375:21, RegisterRouter.scala:83:24]
      priority_16 <= _out_back_io_deq_bits_data[34:32];	// @[Decoupled.scala:375:21, Plic.scala:163:31, RegisterRouter.scala:83:24]
    if (_out_wofireMux_T_2 & _GEN_0 == 7'h9 & _out_T_25 & _out_back_io_deq_bits_mask[0])	// @[Bitwise.scala:28:17, Decoupled.scala:375:21, MuxLiteral.scala:54:22, OneHot.scala:57:35, RegisterRouter.scala:83:24]
      priority_17 <= _out_back_io_deq_bits_data[2:0];	// @[Decoupled.scala:375:21, Plic.scala:163:31, RegisterRouter.scala:83:24]
    if (out_woready_13 & _out_back_io_deq_bits_mask[0])	// @[Bitwise.scala:28:17, Decoupled.scala:375:21, RegisterRouter.scala:83:24]
      threshold_0 <= _out_back_io_deq_bits_data[2:0];	// @[Decoupled.scala:375:21, Plic.scala:166:31, RegisterRouter.scala:83:24]
    if (out_woready_21 & _out_back_io_deq_bits_mask[0])	// @[Bitwise.scala:28:17, Decoupled.scala:375:21, RegisterRouter.scala:83:24]
      enables_0_0 <= _out_back_io_deq_bits_data[7:1];	// @[Decoupled.scala:375:21, Plic.scala:174:26, RegisterRouter.scala:83:24]
    if (out_woready_21 & _out_back_io_deq_bits_mask[1])	// @[Bitwise.scala:28:17, Decoupled.scala:375:21, RegisterRouter.scala:83:24]
      enables_0_1 <= _out_back_io_deq_bits_data[15:8];	// @[Decoupled.scala:375:21, Plic.scala:175:50, RegisterRouter.scala:83:24]
    if (out_woready_21 & _out_back_io_deq_bits_mask[2])	// @[Bitwise.scala:28:17, Decoupled.scala:375:21, RegisterRouter.scala:83:24]
      enables_0_2 <= _out_back_io_deq_bits_data[18:16];	// @[Decoupled.scala:375:21, Plic.scala:176:51, RegisterRouter.scala:83:24]
    maxDevs_0 <= _fanin_io_dev;	// @[Plic.scala:181:22, :184:25]
    x1_0_REG <= _fanin_io_max;	// @[Plic.scala:184:25, :188:45]
    if (reset) begin
      pending_0 <= 1'h0;	// @[Plic.scala:163:31, :168:26]
      pending_1 <= 1'h0;	// @[Plic.scala:163:31, :168:26]
      pending_2 <= 1'h0;	// @[Plic.scala:163:31, :168:26]
      pending_3 <= 1'h0;	// @[Plic.scala:163:31, :168:26]
      pending_4 <= 1'h0;	// @[Plic.scala:163:31, :168:26]
      pending_5 <= 1'h0;	// @[Plic.scala:163:31, :168:26]
      pending_6 <= 1'h0;	// @[Plic.scala:163:31, :168:26]
      pending_7 <= 1'h0;	// @[Plic.scala:163:31, :168:26]
      pending_8 <= 1'h0;	// @[Plic.scala:163:31, :168:26]
      pending_9 <= 1'h0;	// @[Plic.scala:163:31, :168:26]
      pending_10 <= 1'h0;	// @[Plic.scala:163:31, :168:26]
      pending_11 <= 1'h0;	// @[Plic.scala:163:31, :168:26]
      pending_12 <= 1'h0;	// @[Plic.scala:163:31, :168:26]
      pending_13 <= 1'h0;	// @[Plic.scala:163:31, :168:26]
      pending_14 <= 1'h0;	// @[Plic.scala:163:31, :168:26]
      pending_15 <= 1'h0;	// @[Plic.scala:163:31, :168:26]
      pending_16 <= 1'h0;	// @[Plic.scala:163:31, :168:26]
      pending_17 <= 1'h0;	// @[Plic.scala:163:31, :168:26]
    end
    else begin
      if (claimedDevs_1 | _gateways_gateway_io_plic_valid)	// @[OneHot.scala:64:27, Plic.scala:156:27, :247:62, :251:15]
        pending_0 <= ~claimedDevs_1;	// @[OneHot.scala:64:27, Plic.scala:168:26, :247:62, :251:34]
      if (claimedDevs_2 | _gateways_gateway_1_io_plic_valid)	// @[OneHot.scala:64:27, Plic.scala:156:27, :247:62, :251:15]
        pending_1 <= ~claimedDevs_2;	// @[OneHot.scala:64:27, Plic.scala:168:26, :247:62, :251:34]
      if (claimedDevs_3 | _gateways_gateway_2_io_plic_valid)	// @[OneHot.scala:64:27, Plic.scala:156:27, :247:62, :251:15]
        pending_2 <= ~claimedDevs_3;	// @[OneHot.scala:64:27, Plic.scala:168:26, :247:62, :251:34]
      if (claimedDevs_4 | _gateways_gateway_3_io_plic_valid)	// @[OneHot.scala:64:27, Plic.scala:156:27, :247:62, :251:15]
        pending_3 <= ~claimedDevs_4;	// @[OneHot.scala:64:27, Plic.scala:168:26, :247:62, :251:34]
      if (claimedDevs_5 | _gateways_gateway_4_io_plic_valid)	// @[OneHot.scala:64:27, Plic.scala:156:27, :247:62, :251:15]
        pending_4 <= ~claimedDevs_5;	// @[OneHot.scala:64:27, Plic.scala:168:26, :247:62, :251:34]
      if (claimedDevs_6 | _gateways_gateway_5_io_plic_valid)	// @[OneHot.scala:64:27, Plic.scala:156:27, :247:62, :251:15]
        pending_5 <= ~claimedDevs_6;	// @[OneHot.scala:64:27, Plic.scala:168:26, :247:62, :251:34]
      if (claimedDevs_7 | _gateways_gateway_6_io_plic_valid)	// @[OneHot.scala:64:27, Plic.scala:156:27, :247:62, :251:15]
        pending_6 <= ~claimedDevs_7;	// @[OneHot.scala:64:27, Plic.scala:168:26, :247:62, :251:34]
      if (claimedDevs_8 | _gateways_gateway_7_io_plic_valid)	// @[OneHot.scala:64:27, Plic.scala:156:27, :247:62, :251:15]
        pending_7 <= ~claimedDevs_8;	// @[OneHot.scala:64:27, Plic.scala:168:26, :247:62, :251:34]
      if (claimedDevs_9 | _gateways_gateway_8_io_plic_valid)	// @[OneHot.scala:64:27, Plic.scala:156:27, :247:62, :251:15]
        pending_8 <= ~claimedDevs_9;	// @[OneHot.scala:64:27, Plic.scala:168:26, :247:62, :251:34]
      if (claimedDevs_10 | _gateways_gateway_9_io_plic_valid)	// @[OneHot.scala:64:27, Plic.scala:156:27, :247:62, :251:15]
        pending_9 <= ~claimedDevs_10;	// @[OneHot.scala:64:27, Plic.scala:168:26, :247:62, :251:34]
      if (claimedDevs_11 | _gateways_gateway_10_io_plic_valid)	// @[OneHot.scala:64:27, Plic.scala:156:27, :247:62, :251:15]
        pending_10 <= ~claimedDevs_11;	// @[OneHot.scala:64:27, Plic.scala:168:26, :247:62, :251:34]
      if (claimedDevs_12 | _gateways_gateway_11_io_plic_valid)	// @[OneHot.scala:64:27, Plic.scala:156:27, :247:62, :251:15]
        pending_11 <= ~claimedDevs_12;	// @[OneHot.scala:64:27, Plic.scala:168:26, :247:62, :251:34]
      if (claimedDevs_13 | _gateways_gateway_12_io_plic_valid)	// @[OneHot.scala:64:27, Plic.scala:156:27, :247:62, :251:15]
        pending_12 <= ~claimedDevs_13;	// @[OneHot.scala:64:27, Plic.scala:168:26, :247:62, :251:34]
      if (claimedDevs_14 | _gateways_gateway_13_io_plic_valid)	// @[OneHot.scala:64:27, Plic.scala:156:27, :247:62, :251:15]
        pending_13 <= ~claimedDevs_14;	// @[OneHot.scala:64:27, Plic.scala:168:26, :247:62, :251:34]
      if (claimedDevs_15 | _gateways_gateway_14_io_plic_valid)	// @[OneHot.scala:64:27, Plic.scala:156:27, :247:62, :251:15]
        pending_14 <= ~claimedDevs_15;	// @[OneHot.scala:64:27, Plic.scala:168:26, :247:62, :251:34]
      if (claimedDevs_16 | _gateways_gateway_15_io_plic_valid)	// @[OneHot.scala:64:27, Plic.scala:156:27, :247:62, :251:15]
        pending_15 <= ~claimedDevs_16;	// @[OneHot.scala:64:27, Plic.scala:168:26, :247:62, :251:34]
      if (claimedDevs_17 | _gateways_gateway_16_io_plic_valid)	// @[OneHot.scala:64:27, Plic.scala:156:27, :247:62, :251:15]
        pending_16 <= ~claimedDevs_17;	// @[OneHot.scala:64:27, Plic.scala:168:26, :247:62, :251:34]
      if (claimedDevs_18 | _gateways_gateway_17_io_plic_valid)	// @[OneHot.scala:64:27, Plic.scala:156:27, :247:62, :251:15]
        pending_17 <= ~claimedDevs_18;	// @[OneHot.scala:64:27, Plic.scala:168:26, :247:62, :251:34]
    end
  end // always @(posedge)
  `ifndef SYNTHESIS
    always @(posedge clock) begin	// @[Plic.scala:245:11]
      if (~reset & claimer_0 & claimer_0 - 1'h1) begin	// @[Plic.scala:245:{11,46}, RegisterRouter.scala:83:24]
        if (`ASSERT_VERBOSE_COND_)	// @[Plic.scala:245:11]
          $error("Assertion failed\n    at Plic.scala:245 assert((claimer.asUInt & (claimer.asUInt - 1.U)) === 0.U) // One-Hot\n");	// @[Plic.scala:245:11]
        if (`STOP_COND_)	// @[Plic.scala:245:11]
          $fatal;	// @[Plic.scala:245:11]
      end
      if (~reset & completer_0 & completer_0 - 1'h1) begin	// @[Plic.scala:262:{11,50}, :295:35]
        if (`ASSERT_VERBOSE_COND_)	// @[Plic.scala:262:11]
          $error("Assertion failed\n    at Plic.scala:262 assert((completer.asUInt & (completer.asUInt - 1.U)) === 0.U) // One-Hot\n");	// @[Plic.scala:262:11]
        if (`STOP_COND_)	// @[Plic.scala:262:11]
          $fatal;	// @[Plic.scala:262:11]
      end
    end // always @(posedge)
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM_0;
    logic [31:0] _RANDOM_1;
    logic [31:0] _RANDOM_2;
    logic [31:0] _RANDOM_3;
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM_0 = `RANDOM;
        _RANDOM_1 = `RANDOM;
        _RANDOM_2 = `RANDOM;
        _RANDOM_3 = `RANDOM;
        priority_0 = _RANDOM_0[2:0];	// @[Plic.scala:163:31]
        priority_1 = _RANDOM_0[5:3];	// @[Plic.scala:163:31]
        priority_2 = _RANDOM_0[8:6];	// @[Plic.scala:163:31]
        priority_3 = _RANDOM_0[11:9];	// @[Plic.scala:163:31]
        priority_4 = _RANDOM_0[14:12];	// @[Plic.scala:163:31]
        priority_5 = _RANDOM_0[17:15];	// @[Plic.scala:163:31]
        priority_6 = _RANDOM_0[20:18];	// @[Plic.scala:163:31]
        priority_7 = _RANDOM_0[23:21];	// @[Plic.scala:163:31]
        priority_8 = _RANDOM_0[26:24];	// @[Plic.scala:163:31]
        priority_9 = _RANDOM_0[29:27];	// @[Plic.scala:163:31]
        priority_10 = {_RANDOM_0[31:30], _RANDOM_1[0]};	// @[Plic.scala:163:31]
        priority_11 = _RANDOM_1[3:1];	// @[Plic.scala:163:31]
        priority_12 = _RANDOM_1[6:4];	// @[Plic.scala:163:31]
        priority_13 = _RANDOM_1[9:7];	// @[Plic.scala:163:31]
        priority_14 = _RANDOM_1[12:10];	// @[Plic.scala:163:31]
        priority_15 = _RANDOM_1[15:13];	// @[Plic.scala:163:31]
        priority_16 = _RANDOM_1[18:16];	// @[Plic.scala:163:31]
        priority_17 = _RANDOM_1[21:19];	// @[Plic.scala:163:31]
        threshold_0 = _RANDOM_1[24:22];	// @[Plic.scala:163:31, :166:31]
        pending_0 = _RANDOM_1[25];	// @[Plic.scala:163:31, :168:26]
        pending_1 = _RANDOM_1[26];	// @[Plic.scala:163:31, :168:26]
        pending_2 = _RANDOM_1[27];	// @[Plic.scala:163:31, :168:26]
        pending_3 = _RANDOM_1[28];	// @[Plic.scala:163:31, :168:26]
        pending_4 = _RANDOM_1[29];	// @[Plic.scala:163:31, :168:26]
        pending_5 = _RANDOM_1[30];	// @[Plic.scala:163:31, :168:26]
        pending_6 = _RANDOM_1[31];	// @[Plic.scala:163:31, :168:26]
        pending_7 = _RANDOM_2[0];	// @[Plic.scala:168:26]
        pending_8 = _RANDOM_2[1];	// @[Plic.scala:168:26]
        pending_9 = _RANDOM_2[2];	// @[Plic.scala:168:26]
        pending_10 = _RANDOM_2[3];	// @[Plic.scala:168:26]
        pending_11 = _RANDOM_2[4];	// @[Plic.scala:168:26]
        pending_12 = _RANDOM_2[5];	// @[Plic.scala:168:26]
        pending_13 = _RANDOM_2[6];	// @[Plic.scala:168:26]
        pending_14 = _RANDOM_2[7];	// @[Plic.scala:168:26]
        pending_15 = _RANDOM_2[8];	// @[Plic.scala:168:26]
        pending_16 = _RANDOM_2[9];	// @[Plic.scala:168:26]
        pending_17 = _RANDOM_2[10];	// @[Plic.scala:168:26]
        enables_0_0 = _RANDOM_2[17:11];	// @[Plic.scala:168:26, :174:26]
        enables_0_1 = _RANDOM_2[25:18];	// @[Plic.scala:168:26, :175:50]
        enables_0_2 = _RANDOM_2[28:26];	// @[Plic.scala:168:26, :176:51]
        maxDevs_0 = {_RANDOM_2[31:29], _RANDOM_3[1:0]};	// @[Plic.scala:168:26, :181:22]
        x1_0_REG = _RANDOM_3[4:2];	// @[Plic.scala:181:22, :188:45]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // not def SYNTHESIS
  LevelGateway gateways_gateway (	// @[Plic.scala:156:27]
    .clock            (clock),
    .reset            (reset),
    .io_interrupt     (auto_int_in_0),
    .io_plic_ready    (~pending_0),	// @[Plic.scala:168:26, :250:18]
    .io_plic_complete (_GEN[0]),	// @[Plic.scala:264:28, :265:33]
    .io_plic_valid    (_gateways_gateway_io_plic_valid)
  );
  LevelGateway gateways_gateway_1 (	// @[Plic.scala:156:27]
    .clock            (clock),
    .reset            (reset),
    .io_interrupt     (auto_int_in_1),
    .io_plic_ready    (~pending_1),	// @[Plic.scala:168:26, :250:18]
    .io_plic_complete (_GEN[1]),	// @[Plic.scala:264:28, :265:33]
    .io_plic_valid    (_gateways_gateway_1_io_plic_valid)
  );
  LevelGateway gateways_gateway_2 (	// @[Plic.scala:156:27]
    .clock            (clock),
    .reset            (reset),
    .io_interrupt     (auto_int_in_2),
    .io_plic_ready    (~pending_2),	// @[Plic.scala:168:26, :250:18]
    .io_plic_complete (_GEN[2]),	// @[Plic.scala:264:28, :265:33]
    .io_plic_valid    (_gateways_gateway_2_io_plic_valid)
  );
  LevelGateway gateways_gateway_3 (	// @[Plic.scala:156:27]
    .clock            (clock),
    .reset            (reset),
    .io_interrupt     (auto_int_in_3),
    .io_plic_ready    (~pending_3),	// @[Plic.scala:168:26, :250:18]
    .io_plic_complete (_GEN[3]),	// @[Plic.scala:264:28, :265:33]
    .io_plic_valid    (_gateways_gateway_3_io_plic_valid)
  );
  LevelGateway gateways_gateway_4 (	// @[Plic.scala:156:27]
    .clock            (clock),
    .reset            (reset),
    .io_interrupt     (auto_int_in_4),
    .io_plic_ready    (~pending_4),	// @[Plic.scala:168:26, :250:18]
    .io_plic_complete (_GEN[4]),	// @[Plic.scala:264:28, :265:33]
    .io_plic_valid    (_gateways_gateway_4_io_plic_valid)
  );
  LevelGateway gateways_gateway_5 (	// @[Plic.scala:156:27]
    .clock            (clock),
    .reset            (reset),
    .io_interrupt     (auto_int_in_5),
    .io_plic_ready    (~pending_5),	// @[Plic.scala:168:26, :250:18]
    .io_plic_complete (_GEN[5]),	// @[Plic.scala:264:28, :265:33]
    .io_plic_valid    (_gateways_gateway_5_io_plic_valid)
  );
  LevelGateway gateways_gateway_6 (	// @[Plic.scala:156:27]
    .clock            (clock),
    .reset            (reset),
    .io_interrupt     (auto_int_in_6),
    .io_plic_ready    (~pending_6),	// @[Plic.scala:168:26, :250:18]
    .io_plic_complete (_GEN[6]),	// @[Plic.scala:264:28, :265:33]
    .io_plic_valid    (_gateways_gateway_6_io_plic_valid)
  );
  LevelGateway gateways_gateway_7 (	// @[Plic.scala:156:27]
    .clock            (clock),
    .reset            (reset),
    .io_interrupt     (auto_int_in_7),
    .io_plic_ready    (~pending_7),	// @[Plic.scala:168:26, :250:18]
    .io_plic_complete (_GEN[7]),	// @[Plic.scala:264:28, :265:33]
    .io_plic_valid    (_gateways_gateway_7_io_plic_valid)
  );
  LevelGateway gateways_gateway_8 (	// @[Plic.scala:156:27]
    .clock            (clock),
    .reset            (reset),
    .io_interrupt     (auto_int_in_8),
    .io_plic_ready    (~pending_8),	// @[Plic.scala:168:26, :250:18]
    .io_plic_complete (_GEN[8]),	// @[Plic.scala:264:28, :265:33]
    .io_plic_valid    (_gateways_gateway_8_io_plic_valid)
  );
  LevelGateway gateways_gateway_9 (	// @[Plic.scala:156:27]
    .clock            (clock),
    .reset            (reset),
    .io_interrupt     (auto_int_in_9),
    .io_plic_ready    (~pending_9),	// @[Plic.scala:168:26, :250:18]
    .io_plic_complete (_GEN[9]),	// @[Plic.scala:264:28, :265:33]
    .io_plic_valid    (_gateways_gateway_9_io_plic_valid)
  );
  LevelGateway gateways_gateway_10 (	// @[Plic.scala:156:27]
    .clock            (clock),
    .reset            (reset),
    .io_interrupt     (auto_int_in_10),
    .io_plic_ready    (~pending_10),	// @[Plic.scala:168:26, :250:18]
    .io_plic_complete (_GEN[10]),	// @[Plic.scala:264:28, :265:33]
    .io_plic_valid    (_gateways_gateway_10_io_plic_valid)
  );
  LevelGateway gateways_gateway_11 (	// @[Plic.scala:156:27]
    .clock            (clock),
    .reset            (reset),
    .io_interrupt     (auto_int_in_11),
    .io_plic_ready    (~pending_11),	// @[Plic.scala:168:26, :250:18]
    .io_plic_complete (_GEN[11]),	// @[Plic.scala:264:28, :265:33]
    .io_plic_valid    (_gateways_gateway_11_io_plic_valid)
  );
  LevelGateway gateways_gateway_12 (	// @[Plic.scala:156:27]
    .clock            (clock),
    .reset            (reset),
    .io_interrupt     (auto_int_in_12),
    .io_plic_ready    (~pending_12),	// @[Plic.scala:168:26, :250:18]
    .io_plic_complete (_GEN[12]),	// @[Plic.scala:264:28, :265:33]
    .io_plic_valid    (_gateways_gateway_12_io_plic_valid)
  );
  LevelGateway gateways_gateway_13 (	// @[Plic.scala:156:27]
    .clock            (clock),
    .reset            (reset),
    .io_interrupt     (auto_int_in_13),
    .io_plic_ready    (~pending_13),	// @[Plic.scala:168:26, :250:18]
    .io_plic_complete (_GEN[13]),	// @[Plic.scala:264:28, :265:33]
    .io_plic_valid    (_gateways_gateway_13_io_plic_valid)
  );
  LevelGateway gateways_gateway_14 (	// @[Plic.scala:156:27]
    .clock            (clock),
    .reset            (reset),
    .io_interrupt     (auto_int_in_14),
    .io_plic_ready    (~pending_14),	// @[Plic.scala:168:26, :250:18]
    .io_plic_complete (_GEN[14]),	// @[Plic.scala:264:28, :265:33]
    .io_plic_valid    (_gateways_gateway_14_io_plic_valid)
  );
  LevelGateway gateways_gateway_15 (	// @[Plic.scala:156:27]
    .clock            (clock),
    .reset            (reset),
    .io_interrupt     (auto_int_in_15),
    .io_plic_ready    (~pending_15),	// @[Plic.scala:168:26, :250:18]
    .io_plic_complete (_GEN[15]),	// @[Plic.scala:264:28, :265:33]
    .io_plic_valid    (_gateways_gateway_15_io_plic_valid)
  );
  LevelGateway gateways_gateway_16 (	// @[Plic.scala:156:27]
    .clock            (clock),
    .reset            (reset),
    .io_interrupt     (auto_int_in_16),
    .io_plic_ready    (~pending_16),	// @[Plic.scala:168:26, :250:18]
    .io_plic_complete (_GEN[16]),	// @[Plic.scala:264:28, :265:33]
    .io_plic_valid    (_gateways_gateway_16_io_plic_valid)
  );
  LevelGateway gateways_gateway_17 (	// @[Plic.scala:156:27]
    .clock            (clock),
    .reset            (reset),
    .io_interrupt     (auto_int_in_17),
    .io_plic_ready    (~pending_17),	// @[Plic.scala:168:26, :250:18]
    .io_plic_complete (_GEN[17]),	// @[Plic.scala:264:28, :265:33]
    .io_plic_valid    (_gateways_gateway_17_io_plic_valid)
  );
  PLICFanIn fanin (	// @[Plic.scala:184:25]
    .io_prio_0  (priority_0),	// @[Plic.scala:163:31]
    .io_prio_1  (priority_1),	// @[Plic.scala:163:31]
    .io_prio_2  (priority_2),	// @[Plic.scala:163:31]
    .io_prio_3  (priority_3),	// @[Plic.scala:163:31]
    .io_prio_4  (priority_4),	// @[Plic.scala:163:31]
    .io_prio_5  (priority_5),	// @[Plic.scala:163:31]
    .io_prio_6  (priority_6),	// @[Plic.scala:163:31]
    .io_prio_7  (priority_7),	// @[Plic.scala:163:31]
    .io_prio_8  (priority_8),	// @[Plic.scala:163:31]
    .io_prio_9  (priority_9),	// @[Plic.scala:163:31]
    .io_prio_10 (priority_10),	// @[Plic.scala:163:31]
    .io_prio_11 (priority_11),	// @[Plic.scala:163:31]
    .io_prio_12 (priority_12),	// @[Plic.scala:163:31]
    .io_prio_13 (priority_13),	// @[Plic.scala:163:31]
    .io_prio_14 (priority_14),	// @[Plic.scala:163:31]
    .io_prio_15 (priority_15),	// @[Plic.scala:163:31]
    .io_prio_16 (priority_16),	// @[Plic.scala:163:31]
    .io_prio_17 (priority_17),	// @[Plic.scala:163:31]
    .io_ip      ({enables_0_2, enables_0_1, enables_0_0} & {pending_17, pending_16, pending_15, pending_14, pending_13, pending_12, pending_11, pending_10, pending_9, pending_8, pending_7, pending_6, pending_5, pending_4, pending_3, pending_2, pending_1, pending_0}),	// @[Cat.scala:33:92, Plic.scala:168:26, :174:26, :175:50, :176:51, :186:40]
    .io_dev     (_fanin_io_dev),
    .io_max     (_fanin_io_max)
  );
  Queue_74 out_back (	// @[Decoupled.scala:375:21]
    .clock                               (clock),
    .reset                               (reset),
    .io_enq_valid                        (auto_in_a_valid),
    .io_enq_bits_read                    (auto_in_a_bits_opcode == 3'h4),	// @[RegisterRouter.scala:72:36]
    .io_enq_bits_index                   (auto_in_a_bits_address[25:3]),	// @[Edges.scala:192:34, RegisterRouter.scala:73:19]
    .io_enq_bits_data                    (auto_in_a_bits_data),
    .io_enq_bits_mask                    (auto_in_a_bits_mask),
    .io_enq_bits_extra_tlrr_extra_source (auto_in_a_bits_source),
    .io_enq_bits_extra_tlrr_extra_size   (auto_in_a_bits_size),
    .io_deq_ready                        (auto_in_d_ready),
    .io_enq_ready                        (auto_in_a_ready),
    .io_deq_valid                        (_out_back_io_deq_valid),
    .io_deq_bits_read                    (_out_back_io_deq_bits_read),
    .io_deq_bits_index                   (_out_back_io_deq_bits_index),
    .io_deq_bits_data                    (_out_back_io_deq_bits_data),
    .io_deq_bits_mask                    (_out_back_io_deq_bits_mask),
    .io_deq_bits_extra_tlrr_extra_source (auto_in_d_bits_source),
    .io_deq_bits_extra_tlrr_extra_size   (auto_in_d_bits_size)
  );
  assign auto_int_out_0 = x1_0_REG > threshold_0;	// @[Plic.scala:166:31, :188:{45,60}]
  assign auto_in_d_valid = _out_back_io_deq_valid;	// @[Decoupled.scala:375:21]
  assign auto_in_d_bits_opcode = {2'h0, _out_back_io_deq_bits_read};	// @[Decoupled.scala:375:21, MuxLiteral.scala:54:22, RegisterRouter.scala:98:19]
  assign auto_in_d_bits_data = ~(_out_out_bits_data_T_13 | out_oindex == 7'h1 | out_oindex == 7'h2 | out_oindex == 7'h3 | out_oindex == 7'h4 | out_oindex == 7'h5 | out_oindex == 7'h6 | out_oindex == 7'h7 | out_oindex == 7'h8 | out_oindex == 7'h9 | out_oindex == 7'h10 | out_oindex == 7'h20 | out_oindex == 7'h40) | _out_T_25 ? (_out_out_bits_data_T_13 ? {29'h0, priority_0, 32'h0} : out_oindex == 7'h1 ? {29'h0, priority_2, 29'h0, priority_1} : out_oindex == 7'h2 ? {29'h0, priority_4, 29'h0, priority_3} : out_oindex == 7'h3 ? {29'h0, priority_6, 29'h0, priority_5} : out_oindex == 7'h4 ? {29'h0, priority_8, 29'h0, priority_7} : out_oindex == 7'h5 ? {29'h0, priority_10, 29'h0, priority_9} : out_oindex == 7'h6 ? {29'h0, priority_12, 29'h0, priority_11} : out_oindex == 7'h7 ? {29'h0, priority_14, 29'h0, priority_13} : out_oindex == 7'h8 ? {29'h0, priority_16, 29'h0, priority_15} : out_oindex == 7'h9 ? {61'h0, priority_17} : out_oindex == 7'h10 ? {45'h0, pending_17, pending_16, pending_15, pending_14, pending_13, pending_12, pending_11, pending_10, pending_9, pending_8, pending_7, pending_6, pending_5, pending_4, pending_3, pending_2, pending_1, pending_0, 1'h0} : out_oindex == 7'h20 ? {45'h0, enables_0_2, enables_0_1, enables_0_0, 1'h0} : out_oindex == 7'h40 ? {27'h0, maxDevs_0, 29'h0, threshold_0} : 64'h0) : 64'h0;	// @[Cat.scala:33:92, MuxLiteral.scala:52:28, :54:{22,28}, OneHot.scala:64:12, Plic.scala:163:31, :166:31, :168:26, :174:26, :175:50, :176:51, :181:22, RegisterRouter.scala:83:24]
endmodule

