// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

module ClockSinkDomain_3(
  input         auto_gpio_0_control_xing_in_a_valid,
  input  [2:0]  auto_gpio_0_control_xing_in_a_bits_opcode,
  input  [1:0]  auto_gpio_0_control_xing_in_a_bits_size,
  input  [6:0]  auto_gpio_0_control_xing_in_a_bits_source,
  input  [30:0] auto_gpio_0_control_xing_in_a_bits_address,
  input  [7:0]  auto_gpio_0_control_xing_in_a_bits_mask,
  input  [63:0] auto_gpio_0_control_xing_in_a_bits_data,
  input         auto_gpio_0_control_xing_in_d_ready,
                auto_gpio_0_io_out_pins_0_i_ival,
                auto_gpio_0_io_out_pins_1_i_ival,
                auto_gpio_0_io_out_pins_2_i_ival,
                auto_gpio_0_io_out_pins_3_i_ival,
                auto_gpio_0_io_out_pins_4_i_ival,
                auto_gpio_0_io_out_pins_5_i_ival,
                auto_gpio_0_io_out_pins_6_i_ival,
                auto_gpio_0_io_out_pins_7_i_ival,
                auto_gpio_0_io_out_pins_8_i_ival,
                auto_gpio_0_io_out_pins_9_i_ival,
                auto_gpio_0_io_out_pins_10_i_ival,
                auto_gpio_0_io_out_pins_11_i_ival,
                auto_gpio_0_io_out_pins_12_i_ival,
                auto_gpio_0_io_out_pins_13_i_ival,
                auto_gpio_0_io_out_pins_14_i_ival,
                auto_gpio_0_io_out_pins_15_i_ival,
                auto_clock_in_clock,
                auto_clock_in_reset,
  output        auto_gpio_0_int_xing_out_sync_0,
                auto_gpio_0_int_xing_out_sync_1,
                auto_gpio_0_int_xing_out_sync_2,
                auto_gpio_0_int_xing_out_sync_3,
                auto_gpio_0_int_xing_out_sync_4,
                auto_gpio_0_int_xing_out_sync_5,
                auto_gpio_0_int_xing_out_sync_6,
                auto_gpio_0_int_xing_out_sync_7,
                auto_gpio_0_int_xing_out_sync_8,
                auto_gpio_0_int_xing_out_sync_9,
                auto_gpio_0_int_xing_out_sync_10,
                auto_gpio_0_int_xing_out_sync_11,
                auto_gpio_0_int_xing_out_sync_12,
                auto_gpio_0_int_xing_out_sync_13,
                auto_gpio_0_int_xing_out_sync_14,
                auto_gpio_0_int_xing_out_sync_15,
                auto_gpio_0_control_xing_in_a_ready,
                auto_gpio_0_control_xing_in_d_valid,
  output [2:0]  auto_gpio_0_control_xing_in_d_bits_opcode,
  output [1:0]  auto_gpio_0_control_xing_in_d_bits_size,
  output [6:0]  auto_gpio_0_control_xing_in_d_bits_source,
  output [63:0] auto_gpio_0_control_xing_in_d_bits_data,
  output        auto_gpio_0_io_out_pins_0_o_oval,
                auto_gpio_0_io_out_pins_0_o_oe,
                auto_gpio_0_io_out_pins_0_o_ie,
                auto_gpio_0_io_out_pins_0_o_pue,
                auto_gpio_0_io_out_pins_0_o_ds,
                auto_gpio_0_io_out_pins_0_o_ds1,
                auto_gpio_0_io_out_pins_0_o_poe,
                auto_gpio_0_io_out_pins_1_o_oval,
                auto_gpio_0_io_out_pins_1_o_oe,
                auto_gpio_0_io_out_pins_1_o_ie,
                auto_gpio_0_io_out_pins_1_o_pue,
                auto_gpio_0_io_out_pins_1_o_ds,
                auto_gpio_0_io_out_pins_1_o_ds1,
                auto_gpio_0_io_out_pins_1_o_poe,
                auto_gpio_0_io_out_pins_2_o_oval,
                auto_gpio_0_io_out_pins_2_o_oe,
                auto_gpio_0_io_out_pins_2_o_ie,
                auto_gpio_0_io_out_pins_2_o_pue,
                auto_gpio_0_io_out_pins_2_o_ds,
                auto_gpio_0_io_out_pins_2_o_ds1,
                auto_gpio_0_io_out_pins_2_o_poe,
                auto_gpio_0_io_out_pins_3_o_oval,
                auto_gpio_0_io_out_pins_3_o_oe,
                auto_gpio_0_io_out_pins_3_o_ie,
                auto_gpio_0_io_out_pins_3_o_pue,
                auto_gpio_0_io_out_pins_3_o_ds,
                auto_gpio_0_io_out_pins_3_o_ds1,
                auto_gpio_0_io_out_pins_3_o_poe,
                auto_gpio_0_io_out_pins_4_o_oval,
                auto_gpio_0_io_out_pins_4_o_oe,
                auto_gpio_0_io_out_pins_4_o_ie,
                auto_gpio_0_io_out_pins_4_o_pue,
                auto_gpio_0_io_out_pins_4_o_ds,
                auto_gpio_0_io_out_pins_4_o_ds1,
                auto_gpio_0_io_out_pins_4_o_poe,
                auto_gpio_0_io_out_pins_5_o_oval,
                auto_gpio_0_io_out_pins_5_o_oe,
                auto_gpio_0_io_out_pins_5_o_ie,
                auto_gpio_0_io_out_pins_5_o_pue,
                auto_gpio_0_io_out_pins_5_o_ds,
                auto_gpio_0_io_out_pins_5_o_ds1,
                auto_gpio_0_io_out_pins_5_o_poe,
                auto_gpio_0_io_out_pins_6_o_oval,
                auto_gpio_0_io_out_pins_6_o_oe,
                auto_gpio_0_io_out_pins_6_o_ie,
                auto_gpio_0_io_out_pins_6_o_pue,
                auto_gpio_0_io_out_pins_6_o_ds,
                auto_gpio_0_io_out_pins_6_o_ds1,
                auto_gpio_0_io_out_pins_6_o_poe,
                auto_gpio_0_io_out_pins_7_o_oval,
                auto_gpio_0_io_out_pins_7_o_oe,
                auto_gpio_0_io_out_pins_7_o_ie,
                auto_gpio_0_io_out_pins_7_o_pue,
                auto_gpio_0_io_out_pins_7_o_ds,
                auto_gpio_0_io_out_pins_7_o_ds1,
                auto_gpio_0_io_out_pins_7_o_poe,
                auto_gpio_0_io_out_pins_8_o_oval,
                auto_gpio_0_io_out_pins_8_o_oe,
                auto_gpio_0_io_out_pins_8_o_ie,
                auto_gpio_0_io_out_pins_8_o_pue,
                auto_gpio_0_io_out_pins_8_o_ds,
                auto_gpio_0_io_out_pins_8_o_ds1,
                auto_gpio_0_io_out_pins_8_o_poe,
                auto_gpio_0_io_out_pins_9_o_oval,
                auto_gpio_0_io_out_pins_9_o_oe,
                auto_gpio_0_io_out_pins_9_o_ie,
                auto_gpio_0_io_out_pins_9_o_pue,
                auto_gpio_0_io_out_pins_9_o_ds,
                auto_gpio_0_io_out_pins_9_o_ds1,
                auto_gpio_0_io_out_pins_9_o_poe,
                auto_gpio_0_io_out_pins_10_o_oval,
                auto_gpio_0_io_out_pins_10_o_oe,
                auto_gpio_0_io_out_pins_10_o_ie,
                auto_gpio_0_io_out_pins_10_o_pue,
                auto_gpio_0_io_out_pins_10_o_ds,
                auto_gpio_0_io_out_pins_10_o_ds1,
                auto_gpio_0_io_out_pins_10_o_poe,
                auto_gpio_0_io_out_pins_11_o_oval,
                auto_gpio_0_io_out_pins_11_o_oe,
                auto_gpio_0_io_out_pins_11_o_ie,
                auto_gpio_0_io_out_pins_11_o_pue,
                auto_gpio_0_io_out_pins_11_o_ds,
                auto_gpio_0_io_out_pins_11_o_ds1,
                auto_gpio_0_io_out_pins_11_o_poe,
                auto_gpio_0_io_out_pins_12_o_oval,
                auto_gpio_0_io_out_pins_12_o_oe,
                auto_gpio_0_io_out_pins_12_o_ie,
                auto_gpio_0_io_out_pins_12_o_pue,
                auto_gpio_0_io_out_pins_12_o_ds,
                auto_gpio_0_io_out_pins_12_o_ds1,
                auto_gpio_0_io_out_pins_12_o_poe,
                auto_gpio_0_io_out_pins_13_o_oval,
                auto_gpio_0_io_out_pins_13_o_oe,
                auto_gpio_0_io_out_pins_13_o_ie,
                auto_gpio_0_io_out_pins_13_o_pue,
                auto_gpio_0_io_out_pins_13_o_ds,
                auto_gpio_0_io_out_pins_13_o_ds1,
                auto_gpio_0_io_out_pins_13_o_poe,
                auto_gpio_0_io_out_pins_14_o_oval,
                auto_gpio_0_io_out_pins_14_o_oe,
                auto_gpio_0_io_out_pins_14_o_ie,
                auto_gpio_0_io_out_pins_14_o_pue,
                auto_gpio_0_io_out_pins_14_o_ds,
                auto_gpio_0_io_out_pins_14_o_ds1,
                auto_gpio_0_io_out_pins_14_o_poe,
                auto_gpio_0_io_out_pins_15_o_oval,
                auto_gpio_0_io_out_pins_15_o_oe,
                auto_gpio_0_io_out_pins_15_o_ie,
                auto_gpio_0_io_out_pins_15_o_pue,
                auto_gpio_0_io_out_pins_15_o_ds,
                auto_gpio_0_io_out_pins_15_o_ds1,
                auto_gpio_0_io_out_pins_15_o_poe
);

  TLGPIO gpio_0 (	// @[GPIO.scala:267:51]
    .clock                               (auto_clock_in_clock),
    .reset                               (auto_clock_in_reset),
    .auto_control_xing_in_a_valid        (auto_gpio_0_control_xing_in_a_valid),
    .auto_control_xing_in_a_bits_opcode  (auto_gpio_0_control_xing_in_a_bits_opcode),
    .auto_control_xing_in_a_bits_size    (auto_gpio_0_control_xing_in_a_bits_size),
    .auto_control_xing_in_a_bits_source  (auto_gpio_0_control_xing_in_a_bits_source),
    .auto_control_xing_in_a_bits_address (auto_gpio_0_control_xing_in_a_bits_address),
    .auto_control_xing_in_a_bits_mask    (auto_gpio_0_control_xing_in_a_bits_mask),
    .auto_control_xing_in_a_bits_data    (auto_gpio_0_control_xing_in_a_bits_data),
    .auto_control_xing_in_d_ready        (auto_gpio_0_control_xing_in_d_ready),
    .auto_io_out_pins_0_i_ival           (auto_gpio_0_io_out_pins_0_i_ival),
    .auto_io_out_pins_1_i_ival           (auto_gpio_0_io_out_pins_1_i_ival),
    .auto_io_out_pins_2_i_ival           (auto_gpio_0_io_out_pins_2_i_ival),
    .auto_io_out_pins_3_i_ival           (auto_gpio_0_io_out_pins_3_i_ival),
    .auto_io_out_pins_4_i_ival           (auto_gpio_0_io_out_pins_4_i_ival),
    .auto_io_out_pins_5_i_ival           (auto_gpio_0_io_out_pins_5_i_ival),
    .auto_io_out_pins_6_i_ival           (auto_gpio_0_io_out_pins_6_i_ival),
    .auto_io_out_pins_7_i_ival           (auto_gpio_0_io_out_pins_7_i_ival),
    .auto_io_out_pins_8_i_ival           (auto_gpio_0_io_out_pins_8_i_ival),
    .auto_io_out_pins_9_i_ival           (auto_gpio_0_io_out_pins_9_i_ival),
    .auto_io_out_pins_10_i_ival          (auto_gpio_0_io_out_pins_10_i_ival),
    .auto_io_out_pins_11_i_ival          (auto_gpio_0_io_out_pins_11_i_ival),
    .auto_io_out_pins_12_i_ival          (auto_gpio_0_io_out_pins_12_i_ival),
    .auto_io_out_pins_13_i_ival          (auto_gpio_0_io_out_pins_13_i_ival),
    .auto_io_out_pins_14_i_ival          (auto_gpio_0_io_out_pins_14_i_ival),
    .auto_io_out_pins_15_i_ival          (auto_gpio_0_io_out_pins_15_i_ival),
    .auto_int_xing_out_sync_0            (auto_gpio_0_int_xing_out_sync_0),
    .auto_int_xing_out_sync_1            (auto_gpio_0_int_xing_out_sync_1),
    .auto_int_xing_out_sync_2            (auto_gpio_0_int_xing_out_sync_2),
    .auto_int_xing_out_sync_3            (auto_gpio_0_int_xing_out_sync_3),
    .auto_int_xing_out_sync_4            (auto_gpio_0_int_xing_out_sync_4),
    .auto_int_xing_out_sync_5            (auto_gpio_0_int_xing_out_sync_5),
    .auto_int_xing_out_sync_6            (auto_gpio_0_int_xing_out_sync_6),
    .auto_int_xing_out_sync_7            (auto_gpio_0_int_xing_out_sync_7),
    .auto_int_xing_out_sync_8            (auto_gpio_0_int_xing_out_sync_8),
    .auto_int_xing_out_sync_9            (auto_gpio_0_int_xing_out_sync_9),
    .auto_int_xing_out_sync_10           (auto_gpio_0_int_xing_out_sync_10),
    .auto_int_xing_out_sync_11           (auto_gpio_0_int_xing_out_sync_11),
    .auto_int_xing_out_sync_12           (auto_gpio_0_int_xing_out_sync_12),
    .auto_int_xing_out_sync_13           (auto_gpio_0_int_xing_out_sync_13),
    .auto_int_xing_out_sync_14           (auto_gpio_0_int_xing_out_sync_14),
    .auto_int_xing_out_sync_15           (auto_gpio_0_int_xing_out_sync_15),
    .auto_control_xing_in_a_ready        (auto_gpio_0_control_xing_in_a_ready),
    .auto_control_xing_in_d_valid        (auto_gpio_0_control_xing_in_d_valid),
    .auto_control_xing_in_d_bits_opcode  (auto_gpio_0_control_xing_in_d_bits_opcode),
    .auto_control_xing_in_d_bits_size    (auto_gpio_0_control_xing_in_d_bits_size),
    .auto_control_xing_in_d_bits_source  (auto_gpio_0_control_xing_in_d_bits_source),
    .auto_control_xing_in_d_bits_data    (auto_gpio_0_control_xing_in_d_bits_data),
    .auto_io_out_pins_0_o_oval           (auto_gpio_0_io_out_pins_0_o_oval),
    .auto_io_out_pins_0_o_oe             (auto_gpio_0_io_out_pins_0_o_oe),
    .auto_io_out_pins_0_o_ie             (auto_gpio_0_io_out_pins_0_o_ie),
    .auto_io_out_pins_0_o_pue            (auto_gpio_0_io_out_pins_0_o_pue),
    .auto_io_out_pins_0_o_ds             (auto_gpio_0_io_out_pins_0_o_ds),
    .auto_io_out_pins_0_o_ds1            (auto_gpio_0_io_out_pins_0_o_ds1),
    .auto_io_out_pins_0_o_poe            (auto_gpio_0_io_out_pins_0_o_poe),
    .auto_io_out_pins_1_o_oval           (auto_gpio_0_io_out_pins_1_o_oval),
    .auto_io_out_pins_1_o_oe             (auto_gpio_0_io_out_pins_1_o_oe),
    .auto_io_out_pins_1_o_ie             (auto_gpio_0_io_out_pins_1_o_ie),
    .auto_io_out_pins_1_o_pue            (auto_gpio_0_io_out_pins_1_o_pue),
    .auto_io_out_pins_1_o_ds             (auto_gpio_0_io_out_pins_1_o_ds),
    .auto_io_out_pins_1_o_ds1            (auto_gpio_0_io_out_pins_1_o_ds1),
    .auto_io_out_pins_1_o_poe            (auto_gpio_0_io_out_pins_1_o_poe),
    .auto_io_out_pins_2_o_oval           (auto_gpio_0_io_out_pins_2_o_oval),
    .auto_io_out_pins_2_o_oe             (auto_gpio_0_io_out_pins_2_o_oe),
    .auto_io_out_pins_2_o_ie             (auto_gpio_0_io_out_pins_2_o_ie),
    .auto_io_out_pins_2_o_pue            (auto_gpio_0_io_out_pins_2_o_pue),
    .auto_io_out_pins_2_o_ds             (auto_gpio_0_io_out_pins_2_o_ds),
    .auto_io_out_pins_2_o_ds1            (auto_gpio_0_io_out_pins_2_o_ds1),
    .auto_io_out_pins_2_o_poe            (auto_gpio_0_io_out_pins_2_o_poe),
    .auto_io_out_pins_3_o_oval           (auto_gpio_0_io_out_pins_3_o_oval),
    .auto_io_out_pins_3_o_oe             (auto_gpio_0_io_out_pins_3_o_oe),
    .auto_io_out_pins_3_o_ie             (auto_gpio_0_io_out_pins_3_o_ie),
    .auto_io_out_pins_3_o_pue            (auto_gpio_0_io_out_pins_3_o_pue),
    .auto_io_out_pins_3_o_ds             (auto_gpio_0_io_out_pins_3_o_ds),
    .auto_io_out_pins_3_o_ds1            (auto_gpio_0_io_out_pins_3_o_ds1),
    .auto_io_out_pins_3_o_poe            (auto_gpio_0_io_out_pins_3_o_poe),
    .auto_io_out_pins_4_o_oval           (auto_gpio_0_io_out_pins_4_o_oval),
    .auto_io_out_pins_4_o_oe             (auto_gpio_0_io_out_pins_4_o_oe),
    .auto_io_out_pins_4_o_ie             (auto_gpio_0_io_out_pins_4_o_ie),
    .auto_io_out_pins_4_o_pue            (auto_gpio_0_io_out_pins_4_o_pue),
    .auto_io_out_pins_4_o_ds             (auto_gpio_0_io_out_pins_4_o_ds),
    .auto_io_out_pins_4_o_ds1            (auto_gpio_0_io_out_pins_4_o_ds1),
    .auto_io_out_pins_4_o_poe            (auto_gpio_0_io_out_pins_4_o_poe),
    .auto_io_out_pins_5_o_oval           (auto_gpio_0_io_out_pins_5_o_oval),
    .auto_io_out_pins_5_o_oe             (auto_gpio_0_io_out_pins_5_o_oe),
    .auto_io_out_pins_5_o_ie             (auto_gpio_0_io_out_pins_5_o_ie),
    .auto_io_out_pins_5_o_pue            (auto_gpio_0_io_out_pins_5_o_pue),
    .auto_io_out_pins_5_o_ds             (auto_gpio_0_io_out_pins_5_o_ds),
    .auto_io_out_pins_5_o_ds1            (auto_gpio_0_io_out_pins_5_o_ds1),
    .auto_io_out_pins_5_o_poe            (auto_gpio_0_io_out_pins_5_o_poe),
    .auto_io_out_pins_6_o_oval           (auto_gpio_0_io_out_pins_6_o_oval),
    .auto_io_out_pins_6_o_oe             (auto_gpio_0_io_out_pins_6_o_oe),
    .auto_io_out_pins_6_o_ie             (auto_gpio_0_io_out_pins_6_o_ie),
    .auto_io_out_pins_6_o_pue            (auto_gpio_0_io_out_pins_6_o_pue),
    .auto_io_out_pins_6_o_ds             (auto_gpio_0_io_out_pins_6_o_ds),
    .auto_io_out_pins_6_o_ds1            (auto_gpio_0_io_out_pins_6_o_ds1),
    .auto_io_out_pins_6_o_poe            (auto_gpio_0_io_out_pins_6_o_poe),
    .auto_io_out_pins_7_o_oval           (auto_gpio_0_io_out_pins_7_o_oval),
    .auto_io_out_pins_7_o_oe             (auto_gpio_0_io_out_pins_7_o_oe),
    .auto_io_out_pins_7_o_ie             (auto_gpio_0_io_out_pins_7_o_ie),
    .auto_io_out_pins_7_o_pue            (auto_gpio_0_io_out_pins_7_o_pue),
    .auto_io_out_pins_7_o_ds             (auto_gpio_0_io_out_pins_7_o_ds),
    .auto_io_out_pins_7_o_ds1            (auto_gpio_0_io_out_pins_7_o_ds1),
    .auto_io_out_pins_7_o_poe            (auto_gpio_0_io_out_pins_7_o_poe),
    .auto_io_out_pins_8_o_oval           (auto_gpio_0_io_out_pins_8_o_oval),
    .auto_io_out_pins_8_o_oe             (auto_gpio_0_io_out_pins_8_o_oe),
    .auto_io_out_pins_8_o_ie             (auto_gpio_0_io_out_pins_8_o_ie),
    .auto_io_out_pins_8_o_pue            (auto_gpio_0_io_out_pins_8_o_pue),
    .auto_io_out_pins_8_o_ds             (auto_gpio_0_io_out_pins_8_o_ds),
    .auto_io_out_pins_8_o_ds1            (auto_gpio_0_io_out_pins_8_o_ds1),
    .auto_io_out_pins_8_o_poe            (auto_gpio_0_io_out_pins_8_o_poe),
    .auto_io_out_pins_9_o_oval           (auto_gpio_0_io_out_pins_9_o_oval),
    .auto_io_out_pins_9_o_oe             (auto_gpio_0_io_out_pins_9_o_oe),
    .auto_io_out_pins_9_o_ie             (auto_gpio_0_io_out_pins_9_o_ie),
    .auto_io_out_pins_9_o_pue            (auto_gpio_0_io_out_pins_9_o_pue),
    .auto_io_out_pins_9_o_ds             (auto_gpio_0_io_out_pins_9_o_ds),
    .auto_io_out_pins_9_o_ds1            (auto_gpio_0_io_out_pins_9_o_ds1),
    .auto_io_out_pins_9_o_poe            (auto_gpio_0_io_out_pins_9_o_poe),
    .auto_io_out_pins_10_o_oval          (auto_gpio_0_io_out_pins_10_o_oval),
    .auto_io_out_pins_10_o_oe            (auto_gpio_0_io_out_pins_10_o_oe),
    .auto_io_out_pins_10_o_ie            (auto_gpio_0_io_out_pins_10_o_ie),
    .auto_io_out_pins_10_o_pue           (auto_gpio_0_io_out_pins_10_o_pue),
    .auto_io_out_pins_10_o_ds            (auto_gpio_0_io_out_pins_10_o_ds),
    .auto_io_out_pins_10_o_ds1           (auto_gpio_0_io_out_pins_10_o_ds1),
    .auto_io_out_pins_10_o_poe           (auto_gpio_0_io_out_pins_10_o_poe),
    .auto_io_out_pins_11_o_oval          (auto_gpio_0_io_out_pins_11_o_oval),
    .auto_io_out_pins_11_o_oe            (auto_gpio_0_io_out_pins_11_o_oe),
    .auto_io_out_pins_11_o_ie            (auto_gpio_0_io_out_pins_11_o_ie),
    .auto_io_out_pins_11_o_pue           (auto_gpio_0_io_out_pins_11_o_pue),
    .auto_io_out_pins_11_o_ds            (auto_gpio_0_io_out_pins_11_o_ds),
    .auto_io_out_pins_11_o_ds1           (auto_gpio_0_io_out_pins_11_o_ds1),
    .auto_io_out_pins_11_o_poe           (auto_gpio_0_io_out_pins_11_o_poe),
    .auto_io_out_pins_12_o_oval          (auto_gpio_0_io_out_pins_12_o_oval),
    .auto_io_out_pins_12_o_oe            (auto_gpio_0_io_out_pins_12_o_oe),
    .auto_io_out_pins_12_o_ie            (auto_gpio_0_io_out_pins_12_o_ie),
    .auto_io_out_pins_12_o_pue           (auto_gpio_0_io_out_pins_12_o_pue),
    .auto_io_out_pins_12_o_ds            (auto_gpio_0_io_out_pins_12_o_ds),
    .auto_io_out_pins_12_o_ds1           (auto_gpio_0_io_out_pins_12_o_ds1),
    .auto_io_out_pins_12_o_poe           (auto_gpio_0_io_out_pins_12_o_poe),
    .auto_io_out_pins_13_o_oval          (auto_gpio_0_io_out_pins_13_o_oval),
    .auto_io_out_pins_13_o_oe            (auto_gpio_0_io_out_pins_13_o_oe),
    .auto_io_out_pins_13_o_ie            (auto_gpio_0_io_out_pins_13_o_ie),
    .auto_io_out_pins_13_o_pue           (auto_gpio_0_io_out_pins_13_o_pue),
    .auto_io_out_pins_13_o_ds            (auto_gpio_0_io_out_pins_13_o_ds),
    .auto_io_out_pins_13_o_ds1           (auto_gpio_0_io_out_pins_13_o_ds1),
    .auto_io_out_pins_13_o_poe           (auto_gpio_0_io_out_pins_13_o_poe),
    .auto_io_out_pins_14_o_oval          (auto_gpio_0_io_out_pins_14_o_oval),
    .auto_io_out_pins_14_o_oe            (auto_gpio_0_io_out_pins_14_o_oe),
    .auto_io_out_pins_14_o_ie            (auto_gpio_0_io_out_pins_14_o_ie),
    .auto_io_out_pins_14_o_pue           (auto_gpio_0_io_out_pins_14_o_pue),
    .auto_io_out_pins_14_o_ds            (auto_gpio_0_io_out_pins_14_o_ds),
    .auto_io_out_pins_14_o_ds1           (auto_gpio_0_io_out_pins_14_o_ds1),
    .auto_io_out_pins_14_o_poe           (auto_gpio_0_io_out_pins_14_o_poe),
    .auto_io_out_pins_15_o_oval          (auto_gpio_0_io_out_pins_15_o_oval),
    .auto_io_out_pins_15_o_oe            (auto_gpio_0_io_out_pins_15_o_oe),
    .auto_io_out_pins_15_o_ie            (auto_gpio_0_io_out_pins_15_o_ie),
    .auto_io_out_pins_15_o_pue           (auto_gpio_0_io_out_pins_15_o_pue),
    .auto_io_out_pins_15_o_ds            (auto_gpio_0_io_out_pins_15_o_ds),
    .auto_io_out_pins_15_o_ds1           (auto_gpio_0_io_out_pins_15_o_ds1),
    .auto_io_out_pins_15_o_poe           (auto_gpio_0_io_out_pins_15_o_poe)
  );
endmodule

