# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/binhkieudo/Workspace/riscv_framework/fpga/fpga-shells/xilinx/arty_a7_100/constraints/arty-config.xdc

# XDC: /home/binhkieudo/Workspace/riscv_framework/fpga/fpga-shells/xilinx/arty_a7_100/constraints/arty-master.xdc

# XDC: /home/binhkieudo/Workspace/riscv_framework/fpga/generated-src/chipyard.fpga.arty100t.Arty100THarness.RocketArty100TConfig/chipyard.fpga.arty100t.Arty100THarness.RocketArty100TConfig.shell.sdc

# XDC: /home/binhkieudo/Workspace/riscv_framework/fpga/generated-src/chipyard.fpga.arty100t.Arty100THarness.RocketArty100TConfig/chipyard.fpga.arty100t.Arty100THarness.RocketArty100TConfig.shell.xdc

# IP: /home/binhkieudo/Workspace/riscv_framework/fpga/generated-src/chipyard.fpga.arty100t.Arty100THarness.RocketArty100TConfig/obj/ip/harnessSysPLLNode/harnessSysPLLNode.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==harnessSysPLLNode || ORIG_REF_NAME==harnessSysPLLNode} -quiet] -quiet

# IP: /home/binhkieudo/Workspace/riscv_framework/fpga/generated-src/chipyard.fpga.arty100t.Arty100THarness.RocketArty100TConfig/obj/ip/arty100tmig/arty100tmig.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arty100tmig || ORIG_REF_NAME==arty100tmig} -quiet] -quiet

# XDC: /home/binhkieudo/Workspace/riscv_framework/fpga/generated-src/chipyard.fpga.arty100t.Arty100THarness.RocketArty100TConfig/obj/ip/harnessSysPLLNode/harnessSysPLLNode_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==harnessSysPLLNode || ORIG_REF_NAME==harnessSysPLLNode} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/binhkieudo/Workspace/riscv_framework/fpga/generated-src/chipyard.fpga.arty100t.Arty100THarness.RocketArty100TConfig/obj/ip/harnessSysPLLNode/harnessSysPLLNode.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==harnessSysPLLNode || ORIG_REF_NAME==harnessSysPLLNode} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/binhkieudo/Workspace/riscv_framework/fpga/generated-src/chipyard.fpga.arty100t.Arty100THarness.RocketArty100TConfig/obj/ip/harnessSysPLLNode/harnessSysPLLNode_late.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==harnessSysPLLNode || ORIG_REF_NAME==harnessSysPLLNode} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/binhkieudo/Workspace/riscv_framework/fpga/generated-src/chipyard.fpga.arty100t.Arty100THarness.RocketArty100TConfig/obj/ip/harnessSysPLLNode/harnessSysPLLNode_ooc.xdc

# XDC: /home/binhkieudo/Workspace/riscv_framework/fpga/generated-src/chipyard.fpga.arty100t.Arty100THarness.RocketArty100TConfig/obj/ip/arty100tmig/arty100tmig/user_design/constraints/arty100tmig.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==arty100tmig || ORIG_REF_NAME==arty100tmig} -quiet] -quiet

# XDC: /home/binhkieudo/Workspace/riscv_framework/fpga/generated-src/chipyard.fpga.arty100t.Arty100THarness.RocketArty100TConfig/obj/ip/arty100tmig/arty100tmig/user_design/constraints/arty100tmig_ooc.xdc
